<div class="class-header">
    <h1 class="class-name"><?= $className ?></h1>
    <div class="class-type">Class</div>
</div>


<div class="methods-summary standard-bandeau">Methods</div>
<ul class="method-summary-list">
    <?php foreach($methods as $method){ ?>

        <?= $this->partial("class/method-summary.phtml",array("method"=>$method)) ?>

    <?php } ?>
</ul>

<div class="methods-summary standard-bandeau">Methods Details</div>
<ul class="method-details-list">
    <?php foreach($methods as $method){ ?>

        <?= $this->partial("class/method-details.phtml",array("method"=>$method)) ?>

    <?php } ?>
</ul>