<?php

/* @var $method \Zephir\ClassMethod */

?>

<li class="class-method clearfix">

    <div class="method-return">

        <?php

            $allTypes = array();

            if($method->getReturnClassTypes()){
                $allTypes = array_merge($allTypes,$method->getReturnClassTypes());

            }


            $types = $method->getReturnTypes();

            if($types && count($types)>0 ){

                foreach($types as $type){

                    if($type && isset($type["data-type"]))
                        $allTypes[] =  $type["data-type"];
                }
            }

            echo implode("|",$allTypes);

        ?>

    </div>
    <div class="method-summary">
        <span class="method-name"><?= $method->getName() ?></span>(<?= $this->partial("class/method-summary-params.phtml" ) ?>)

    </div>

</li>