
extern zend_class_entry *stub_properties_extendspublicproperties_ce;

ZEPHIR_INIT_CLASS(Stub_Properties_ExtendsPublicProperties);

zend_object *zephir_init_properties_Stub_Properties_ExtendsPublicProperties(zend_class_entry *class_type);

ZEPHIR_INIT_FUNCS(stub_properties_extendspublicproperties_method_entry) {
	PHP_FE_END
};
