
extern zend_class_entry *stub_properties_extendspublicproperties_ce;

ZEPHIR_INIT_CLASS(Stub_Properties_ExtendsPublicProperties);

zend_object *zephir_init_properties_Stub_Properties_ExtendsPublicProperties(zend_class_entry *class_type);

ZEND_BEGIN_ARG_INFO_EX(arginfo_stub_properties_extendspublicproperties_zephir_init_properties_stub_properties_extendspublicproperties, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(stub_properties_extendspublicproperties_method_entry) {
	PHP_FE_END
};
