
extern zend_class_entry *stub_properties_staticpropertyarray_ce;

ZEPHIR_INIT_CLASS(Stub_Properties_StaticPropertyArray);

void zephir_init_static_properties_Stub_Properties_StaticPropertyArray();

ZEPHIR_INIT_FUNCS(stub_properties_staticpropertyarray_method_entry) {
	PHP_FE_END
};
