codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "35...90"

  status:
    project:
      default:
        # Allow the coverage to drop by threshold %, and posting a success status.
        threshold: 0.5
    patch:
      default:
        # trial operation
        target: 0%
    changes: no

comment:
  layout: diff
  behavior: default
  require_changes: false

ignore:
  - ".git"
  - "*.yml"
  - "*.json"
  - "*.md"
  - "*.mk"
  # ignore folders and all its contents
  - ".ci/.*"
  - ".github/.*"
  - ".zephir/.*"
  - "ide/.*"
  - "/home/travis/.phpenv/.*"
  - "php-zephir-parser/.*"
  - ".phpunit/.*"
  - "tests/.*"
  - "vendor/.*"
