#!/bin/bash

ZEPHIRDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
sed "s#%ZEPHIRDIR%#$ZEPHIRDIR#g" bin/zephir > bin/zephir-cmd
chmod 755 bin/zephir-cmd

if [ ! -d "~/bin" ]; then
	mkdir -p ~/bin
fi

cp bin/zephir-cmd ~/bin/zephir
rm bin/zephir-cmd
