#!/bin/bash
cd parser
rm -f *.o
rm -f *.lo
if [ ! -f lemon ]; then
	gcc -g lemon.c -o lemon
fi
re2c -o scanner.c scanner.re && ./lemon -s parser.lemon && cat base.c >> parser.c
sed s/"\#line"/"\/\/"/g scanner.c > xx && mv -f xx scanner.c
sed s/"#line"/"\/\/"/g parser.c > xx && mv -f xx parser.c
#sed s/"YY"/"JJ"/g parser.c > xx && mv -f xx parser.c
#sed s/"yy"/"jj"/g parser.c > xx && mv -f xx parser.c
#sed s/"TOKEN"/"JTOKEN"/g parser.c > xx && mv -f xx parser.c
#sed s/"YY"/"JJ"/g scanner.c > xx && mv -f xx scanner.c
#sed s/"yy"/"jj"/g scanner.c > xx && mv -f xx scanner.c
export CFLAGS="-O2"
gcc -Wl,-rpath /usr/local/lib -I/usr/local/lib -L/usr/local/lib -L/opt/local/lib -g3 parser.c scanner.c -ljson -ljson-c -o ../bin/zephir-parser
