#define XX_COMMA                           1
#define XX_EQUALS                          2
#define XX_IDENTICAL                       3
#define XX_NEW                             4
#define XX_NAMESPACE                       5
#define XX_IDENTIFIER                      6
#define XX_DOTCOMMA                        7
#define XX_CLASS                           8
#define XX_BRACKET_OPEN                    9
#define XX_BRACKET_CLOSE                  10
#define XX_EXTENDS                        11
#define XX_ABSTRACT                       12
#define XX_COMMENT                        13
#define XX_PUBLIC                         14
#define XX_ASSIGN                         15
#define XX_PROTECTED                      16
#define XX_CONST                          17
#define XX_FUNCTION                       18
#define XX_PARENTHESES_OPEN               19
#define XX_PARENTHESES_CLOSE              20
#define XX_LESS                           21
#define XX_GREATER                        22
#define XX_TYPE_INTEGER                   23
#define XX_TYPE_DOUBLE                    24
#define XX_TYPE_BOOL                      25
#define XX_TYPE_STRING                    26
#define XX_TYPE_ARRAY                     27
#define XX_IF                             28
#define XX_LET                            29
#define XX_ARROW                          30
#define XX_SBRACKET_OPEN                  31
#define XX_SBRACKET_CLOSE                 32
#define XX_ECHO                           33
#define XX_TYPE_VAR                       34
#define XX_INTEGER                        35
#define XX_STRING                         36
#define XX_DOUBLE                         37
#define XX_NULL                           38
#define XX_FALSE                          39
#define XX_COLON                          40
#define XX_TRUE                           41
