#define XX_COMMA                           1
#define XX_EQUALS                          2
#define XX_IDENTICAL                       3
#define XX_LESS                            4
#define XX_GREATER                         5
#define XX_NOTIDENTICAL                    6
#define XX_NOTEQUALS                       7
#define XX_ADD                             8
#define XX_SUB                             9
#define XX_CONCAT                         10
#define XX_ISSET                          11
#define XX_TYPEOF                         12
#define XX_INSTANCEOF                     13
#define XX_NEW                            14
#define XX_NOT                            15
#define XX_NAMESPACE                      16
#define XX_IDENTIFIER                     17
#define XX_DOTCOMMA                       18
#define XX_CLASS                          19
#define XX_BRACKET_OPEN                   20
#define XX_BRACKET_CLOSE                  21
#define XX_EXTENDS                        22
#define XX_ABSTRACT                       23
#define XX_COMMENT                        24
#define XX_PUBLIC                         25
#define XX_ASSIGN                         26
#define XX_PROTECTED                      27
#define XX_CONST                          28
#define XX_FUNCTION                       29
#define XX_PARENTHESES_OPEN               30
#define XX_PARENTHESES_CLOSE              31
#define XX_TYPE_INTEGER                   32
#define XX_TYPE_DOUBLE                    33
#define XX_TYPE_BOOL                      34
#define XX_TYPE_STRING                    35
#define XX_TYPE_ARRAY                     36
#define XX_BREAK                          37
#define XX_CONTINUE                       38
#define XX_IF                             39
#define XX_ELSE                           40
#define XX_LOOP                           41
#define XX_WHILE                          42
#define XX_FOR                            43
#define XX_IN                             44
#define XX_LET                            45
#define XX_ARROW                          46
#define XX_SBRACKET_OPEN                  47
#define XX_SBRACKET_CLOSE                 48
#define XX_INCR                           49
#define XX_DECR                           50
#define XX_ECHO                           51
#define XX_RETURN                         52
#define XX_UNSET                          53
#define XX_INTEGER                        54
#define XX_STRING                         55
#define XX_THROW                          56
#define XX_TYPE_VAR                       57
#define XX_DOUBLE                         58
#define XX_NULL                           59
#define XX_TRUE                           60
#define XX_FALSE                          61
#define XX_COLON                          62
