#define XX_COMMA                           1
#define XX_AND                             2
#define XX_OR                              3
#define XX_EQUALS                          4
#define XX_IDENTICAL                       5
#define XX_LESS                            6
#define XX_GREATER                         7
#define XX_LESSEQUAL                       8
#define XX_GREATEREQUAL                    9
#define XX_NOTIDENTICAL                   10
#define XX_NOTEQUALS                      11
#define XX_ADD                            12
#define XX_SUB                            13
#define XX_CONCAT                         14
#define XX_ISSET                          15
#define XX_FETCH                          16
#define XX_TYPEOF                         17
#define XX_INSTANCEOF                     18
#define XX_NEW                            19
#define XX_NOT                            20
#define XX_NAMESPACE                      21
#define XX_IDENTIFIER                     22
#define XX_DOTCOMMA                       23
#define XX_CLASS                          24
#define XX_BRACKET_OPEN                   25
#define XX_BRACKET_CLOSE                  26
#define XX_EXTENDS                        27
#define XX_ABSTRACT                       28
#define XX_COMMENT                        29
#define XX_ASSIGN                         30
#define XX_PUBLIC                         31
#define XX_PROTECTED                      32
#define XX_STATIC                         33
#define XX_PRIVATE                        34
#define XX_CONST                          35
#define XX_FUNCTION                       36
#define XX_PARENTHESES_OPEN               37
#define XX_PARENTHESES_CLOSE              38
#define XX_TYPE_INTEGER                   39
#define XX_TYPE_DOUBLE                    40
#define XX_TYPE_BOOL                      41
#define XX_TYPE_STRING                    42
#define XX_TYPE_ARRAY                     43
#define XX_TYPE_VAR                       44
#define XX_BREAK                          45
#define XX_CONTINUE                       46
#define XX_IF                             47
#define XX_ELSE                           48
#define XX_SWITCH                         49
#define XX_CASE                           50
#define XX_COLON                          51
#define XX_DEFAULT                        52
#define XX_LOOP                           53
#define XX_WHILE                          54
#define XX_FOR                            55
#define XX_IN                             56
#define XX_REVERSE                        57
#define XX_LET                            58
#define XX_ADDASSIGN                      59
#define XX_SUBASSIGN                      60
#define XX_MULASSIGN                      61
#define XX_DIVASSIGN                      62
#define XX_CONCATASSIGN                   63
#define XX_ARROW                          64
#define XX_SBRACKET_OPEN                  65
#define XX_SBRACKET_CLOSE                 66
#define XX_INCR                           67
#define XX_DECR                           68
#define XX_ECHO                           69
#define XX_RETURN                         70
#define XX_UNSET                          71
#define XX_INTEGER                        72
#define XX_STRING                         73
#define XX_THROW                          74
#define XX_DOUBLE                         75
#define XX_NULL                           76
#define XX_TRUE                           77
#define XX_FALSE                          78
