/* Generated by re2c 0.13.5 on Wed Aug 14 09:57:48 2013 */
// 1 "scanner.re"

/*
 +----------------------------------------------------------------------+
 | Zephir Language                                                      |
 +----------------------------------------------------------------------+
 | Copyright (c) 2013 Zephir Team                                       |
 +----------------------------------------------------------------------+
 | This source file is subject to version 1.0 of the Zephir license,    |
 | that is bundled with this package in the file LICENSE, and is        |
 | available through the world-wide-web at the following url:           |
 | http://www.zephir-lang.com/license                                   |
 |                                                                      |
 | If you did not receive a copy of the Zephir license and are unable   |
 | to obtain it through the world-wide-web, please send a note to       |
 | license@zephir-lang.com so we can mail you a copy immediately.       |
 +----------------------------------------------------------------------+
*/

#include "string.h"
#include "scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int xx_get_token(xx_scanner_state *s, xx_scanner_token *token) {

	char next, *q = YYCURSOR, *start = YYCURSOR;
	int status = XX_SCANNER_RETCODE_IMPOSSIBLE;

	while (XX_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
// 38 "scanner.c"
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy68;
			case '\t':
			case '\r':
			case ' ':	goto yy64;
			case '\n':	goto yy66;
			case '!':	goto yy43;
			case '"':	goto yy23;
			case '&':	goto yy45;
			case '\'':	goto yy25;
			case '(':	goto yy29;
			case ')':	goto yy31;
			case '*':	goto yy51;
			case '+':	goto yy49;
			case ',':	goto yy62;
			case '-':	goto yy2;
			case '.':	goto yy52;
			case '/':	goto yy26;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy4;
			case ':':	goto yy58;
			case ';':	goto yy60;
			case '<':	goto yy54;
			case '=':	goto yy47;
			case '>':	goto yy56;
			case '@':	goto yy41;
			case 'A':
			case 'a':	goto yy10;
			case 'B':
			case 'b':	goto yy17;
			case 'C':
			case 'c':	goto yy11;
			case 'D':
			case 'd':	goto yy16;
			case 'E':
			case 'e':	goto yy12;
			case 'F':
			case 'f':	goto yy8;
			case 'G':
			case 'H':
			case 'J':
			case 'K':
			case 'M':
			case 'O':
			case 'Q':
			case 'X':
			case 'Y':
			case 'Z':
			case 'g':
			case 'h':
			case 'j':
			case 'k':
			case 'm':
			case 'o':
			case 'q':
			case 'x':
			case 'y':
			case 'z':	goto yy28;
			case 'I':
			case 'i':	goto yy15;
			case 'L':
			case 'l':	goto yy14;
			case 'N':
			case 'n':	goto yy6;
			case 'P':
			case 'p':	goto yy13;
			case 'R':
			case 'r':	goto yy21;
			case 'S':
			case 's':	goto yy18;
			case 'T':
			case 't':	goto yy9;
			case 'U':
			case 'u':	goto yy22;
			case 'V':
			case 'v':	goto yy19;
			case 'W':
			case 'w':	goto yy20;
			case '[':	goto yy37;
			case '\\':
			case '_':	goto yy27;
			case ']':	goto yy39;
			case '{':	goto yy33;
			case '|':	goto yy46;
			case '}':	goto yy35;
			default:	goto yy70;
			}
yy2:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '-':	goto yy334;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy329;
			case '=':	goto yy338;
			case '>':	goto yy336;
			default:	goto yy3;
			}
yy3:
// 513 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SUB;
			return 0;
		}
// 164 "scanner.c"
yy4:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			goto yy330;
yy5:
// 39 "scanner.re"
			{
			token->opcode = XX_T_INTEGER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 179 "scanner.c"
yy6:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case 'A':
			case 'a':	goto yy312;
			case 'E':
			case 'e':	goto yy313;
			case 'U':
			case 'u':	goto yy314;
			default:	goto yy98;
			}
yy7:
// 342 "scanner.re"
			{
			token->opcode = XX_T_IDENTIFIER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 201 "scanner.c"
yy8:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy284;
			case 'E':
			case 'e':	goto yy285;
			case 'L':
			case 'l':	goto yy286;
			case 'N':
			case 'n':	goto yy287;
			case 'O':
			case 'o':	goto yy289;
			case 'U':
			case 'u':	goto yy290;
			default:	goto yy98;
			}
yy9:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy269;
			case 'R':
			case 'r':	goto yy270;
			case 'Y':
			case 'y':	goto yy271;
			default:	goto yy98;
			}
yy10:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy261;
			default:	goto yy98;
			}
yy11:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy241;
			case 'L':
			case 'l':	goto yy242;
			case 'O':
			case 'o':	goto yy243;
			default:	goto yy98;
			}
yy12:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy226;
			case 'L':
			case 'l':	goto yy227;
			case 'X':
			case 'x':	goto yy228;
			default:	goto yy98;
			}
yy13:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy211;
			case 'U':
			case 'u':	goto yy212;
			default:	goto yy98;
			}
yy14:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy201;
			case 'O':
			case 'o':	goto yy202;
			default:	goto yy98;
			}
yy15:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy181;
			case 'N':
			case 'n':	goto yy183;
			case 'S':
			case 's':	goto yy185;
			default:	goto yy98;
			}
yy16:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy168;
			case 'O':
			case 'o':	goto yy169;
			default:	goto yy98;
			}
yy17:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy155;
			case 'R':
			case 'r':	goto yy156;
			default:	goto yy98;
			}
yy18:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy143;
			case 'W':
			case 'w':	goto yy144;
			default:	goto yy98;
			}
yy19:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy140;
			default:	goto yy98;
			}
yy20:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy135;
			default:	goto yy98;
			}
yy21:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy123;
			default:	goto yy98;
			}
yy22:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy118;
			default:	goto yy98;
			}
yy23:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych >= 0x01) goto yy116;
yy24:
// 567 "scanner.re"
			{
			status = XX_SCANNER_RETCODE_ERR;
			break;
		}
// 353 "scanner.c"
yy25:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy24;
			goto yy110;
yy26:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case '*':	goto yy104;
			case '/':	goto yy101;
			case '=':	goto yy99;
			default:	goto yy24;
			}
yy27:
			yych = *++YYCURSOR;
			goto yy98;
yy28:
			yych = *++YYCURSOR;
			goto yy98;
yy29:
			++YYCURSOR;
// 351 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_PARENTHESES_OPEN;
			return 0;
		}
// 382 "scanner.c"
yy31:
			++YYCURSOR;
// 357 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_PARENTHESES_CLOSE;
			return 0;
		}
// 391 "scanner.c"
yy33:
			++YYCURSOR;
// 363 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_BRACKET_OPEN;
			return 0;
		}
// 400 "scanner.c"
yy35:
			++YYCURSOR;
// 369 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_BRACKET_CLOSE;
			return 0;
		}
// 409 "scanner.c"
yy37:
			++YYCURSOR;
// 375 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SBRACKET_OPEN;
			return 0;
		}
// 418 "scanner.c"
yy39:
			++YYCURSOR;
// 381 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SBRACKET_CLOSE;
			return 0;
		}
// 427 "scanner.c"
yy41:
			++YYCURSOR;
// 387 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_AT;
			return 0;
		}
// 436 "scanner.c"
yy43:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy93;
			default:	goto yy44;
			}
yy44:
// 393 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_NOT;
			return 0;
		}
// 450 "scanner.c"
yy45:
			yych = *++YYCURSOR;
			switch (yych) {
			case '&':	goto yy91;
			default:	goto yy24;
			}
yy46:
			yych = *++YYCURSOR;
			switch (yych) {
			case '|':	goto yy89;
			default:	goto yy24;
			}
yy47:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy85;
			default:	goto yy48;
			}
yy48:
// 411 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_ASSIGN;
			return 0;
		}
// 476 "scanner.c"
yy49:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '+':	goto yy81;
			case '=':	goto yy83;
			default:	goto yy50;
			}
yy50:
// 507 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_ADD;
			return 0;
		}
// 491 "scanner.c"
yy51:
			yych = *++YYCURSOR;
			switch (yych) {
			case '=':	goto yy79;
			default:	goto yy24;
			}
yy52:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy77;
			default:	goto yy53;
			}
yy53:
// 501 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_DOT;
			return 0;
		}
// 511 "scanner.c"
yy54:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy75;
			default:	goto yy55;
			}
yy55:
// 483 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_LESS;
			return 0;
		}
// 525 "scanner.c"
yy56:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy73;
			default:	goto yy57;
			}
yy57:
// 489 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_GREATER;
			return 0;
		}
// 539 "scanner.c"
yy58:
			++YYCURSOR;
// 531 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_COLON;
			return 0;
		}
// 548 "scanner.c"
yy60:
			++YYCURSOR;
// 537 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_DOTCOMMA;
			return 0;
		}
// 557 "scanner.c"
yy62:
			++YYCURSOR;
// 543 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_COMMA;
			return 0;
		}
// 566 "scanner.c"
yy64:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy72;
yy65:
// 549 "scanner.re"
			{
			s->active_char += (YYCURSOR - start);
			token->opcode = XX_T_IGNORE;
			return 0;
		}
// 578 "scanner.c"
yy66:
			++YYCURSOR;
// 555 "scanner.re"
			{
			s->active_line++;
			s->active_char = 0;
			token->opcode = XX_T_IGNORE;
			return 0;
		}
// 588 "scanner.c"
yy68:
			++YYCURSOR;
// 562 "scanner.re"
			{
			status = XX_SCANNER_RETCODE_EOF;
			break;
		}
// 596 "scanner.c"
yy70:
			yych = *++YYCURSOR;
			goto yy24;
yy71:
			++YYCURSOR;
			yych = *YYCURSOR;
yy72:
			switch (yych) {
			case '\t':
			case '\r':
			case ' ':	goto yy71;
			default:	goto yy65;
			}
yy73:
			++YYCURSOR;
// 477 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_GREATEREQUAL;
			return 0;
		}
// 618 "scanner.c"
yy75:
			++YYCURSOR;
// 471 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_LESSEQUAL;
			return 0;
		}
// 627 "scanner.c"
yy77:
			++YYCURSOR;
// 441 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_CONCATASSIGN;
			return 0;
		}
// 636 "scanner.c"
yy79:
			++YYCURSOR;
// 429 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_MULASSIGN;
			return 0;
		}
// 645 "scanner.c"
yy81:
			++YYCURSOR;
// 519 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_INCR;
			return 0;
		}
// 654 "scanner.c"
yy83:
			++YYCURSOR;
// 417 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_ADDASSIGN;
			return 0;
		}
// 663 "scanner.c"
yy85:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy87;
			default:	goto yy86;
			}
yy86:
// 447 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_EQUALS;
			return 0;
		}
// 677 "scanner.c"
yy87:
			++YYCURSOR;
// 459 "scanner.re"
			{
			s->active_char += 3;
			token->opcode = XX_T_IDENTICAL;
			return 0;
		}
// 686 "scanner.c"
yy89:
			++YYCURSOR;
// 405 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_OR;
			return 0;
		}
// 695 "scanner.c"
yy91:
			++YYCURSOR;
// 399 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_AND;
			return 0;
		}
// 704 "scanner.c"
yy93:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy95;
			default:	goto yy94;
			}
yy94:
// 453 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_NOTEQUALS;
			return 0;
		}
// 718 "scanner.c"
yy95:
			++YYCURSOR;
// 465 "scanner.re"
			{
			s->active_char += 3;
			token->opcode = XX_T_NOTIDENTICAL;
			return 0;
		}
// 727 "scanner.c"
yy97:
			++YYCURSOR;
			yych = *YYCURSOR;
yy98:
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy7;
			}
yy99:
			++YYCURSOR;
// 435 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_DIVASSIGN;
			return 0;
		}
// 807 "scanner.c"
yy101:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':
			case '\r':	goto yy103;
			default:	goto yy101;
			}
yy103:
// 321 "scanner.re"
			{
			token->opcode = XX_T_COMMENT;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			{
				int k, ch = s->active_char;
				for (k = 0; k < (token->len - 1); k++) {
					if (token->value[k] == '\n') {
						ch = 1;
						s->active_line++;
					} else {
						ch++;
					}
				}
				s->active_char = ch;
			}
			q = YYCURSOR;
			return 0;
		}
// 837 "scanner.c"
yy104:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':	goto yy106;
			default:	goto yy104;
			}
yy106:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':	goto yy106;
			case '/':	goto yy108;
			default:	goto yy104;
			}
yy108:
			yych = *++YYCURSOR;
			goto yy103;
yy109:
			++YYCURSOR;
			yych = *YYCURSOR;
yy110:
			switch (yych) {
			case 0x00:	goto yy111;
			case '\'':	goto yy113;
			case '\\':	goto yy112;
			default:	goto yy109;
			}
yy111:
			YYCURSOR = YYMARKER;
			switch (yyaccept) {
			case 0: 	goto yy5;
			case 1: 	goto yy24;
			}
yy112:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy111;
			default:	goto yy109;
			}
yy113:
			++YYCURSOR;
// 311 "scanner.re"
			{
			token->opcode = XX_T_STRING;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 890 "scanner.c"
yy115:
			++YYCURSOR;
			yych = *YYCURSOR;
yy116:
			switch (yych) {
			case 0x00:	goto yy111;
			case '"':	goto yy113;
			case '\\':	goto yy117;
			default:	goto yy115;
			}
yy117:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy111;
			default:	goto yy115;
			}
yy118:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy119;
			default:	goto yy98;
			}
yy119:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy120;
			default:	goto yy98;
			}
yy120:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy121;
			default:	goto yy98;
			}
yy121:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy122;
			}
yy122:
// 268 "scanner.re"
			{
			token->opcode = XX_T_UNSET;
			s->active_char += sizeof("unset")-1;
			return 0;
		}
// 1005 "scanner.c"
yy123:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy124;
			case 'V':
			case 'v':	goto yy125;
			default:	goto yy98;
			}
yy124:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy131;
			default:	goto yy98;
			}
yy125:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy126;
			default:	goto yy98;
			}
yy126:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy127;
			default:	goto yy98;
			}
yy127:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy128;
			default:	goto yy98;
			}
yy128:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy129;
			default:	goto yy98;
			}
yy129:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy130;
			}
yy130:
// 304 "scanner.re"
			{
			token->opcode = XX_T_REVERSE;
			s->active_char += sizeof("reverse")-1;
			return 0;
		}
// 1126 "scanner.c"
yy131:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy132;
			default:	goto yy98;
			}
yy132:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy133;
			default:	goto yy98;
			}
yy133:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy134;
			}
yy134:
// 226 "scanner.re"
			{
			s->active_char += sizeof("return")-1;
			token->opcode = XX_T_RETURN;
			return 0;
		}
// 1217 "scanner.c"
yy135:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy136;
			default:	goto yy98;
			}
yy136:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy137;
			default:	goto yy98;
			}
yy137:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy138;
			default:	goto yy98;
			}
yy138:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy139;
			}
yy139:
// 202 "scanner.re"
			{
			s->active_char += sizeof("while")-1;
			token->opcode = XX_T_WHILE;
			return 0;
		}
// 1315 "scanner.c"
yy140:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy141;
			default:	goto yy98;
			}
yy141:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy142;
			}
yy142:
// 184 "scanner.re"
			{
			s->active_char += sizeof("var")-1;
			token->opcode = XX_T_TYPE_VAR;
			return 0;
		}
// 1399 "scanner.c"
yy143:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy150;
			default:	goto yy98;
			}
yy144:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy145;
			default:	goto yy98;
			}
yy145:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy146;
			default:	goto yy98;
			}
yy146:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy147;
			default:	goto yy98;
			}
yy147:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy148;
			default:	goto yy98;
			}
yy148:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy149;
			}
yy149:
// 286 "scanner.re"
			{
			token->opcode = XX_T_SWITCH;
			s->active_char += sizeof("switch")-1;
			return 0;
		}
// 1511 "scanner.c"
yy150:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy151;
			default:	goto yy98;
			}
yy151:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy152;
			default:	goto yy98;
			}
yy152:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy153;
			default:	goto yy98;
			}
yy153:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy154;
			}
yy154:
// 178 "scanner.re"
			{
			s->active_char += sizeof("string")-1;
			token->opcode = XX_T_TYPE_STRING;
			return 0;
		}
// 1609 "scanner.c"
yy155:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy161;
			default:	goto yy98;
			}
yy156:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy157;
			default:	goto yy98;
			}
yy157:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy158;
			default:	goto yy98;
			}
yy158:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'K':
			case 'k':	goto yy159;
			default:	goto yy98;
			}
yy159:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy160;
			}
yy160:
// 238 "scanner.re"
			{
			token->opcode = XX_T_BREAK;
			s->active_char += sizeof("break")-1;
			return 0;
		}
// 1714 "scanner.c"
yy161:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy162;
			default:	goto yy98;
			}
yy162:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			case 'E':
			case 'e':	goto yy164;
			default:	goto yy163;
			}
yy163:
// 166 "scanner.re"
			{
			s->active_char += sizeof("bool")-1;
			token->opcode = XX_T_TYPE_BOOL;
			return 0;
		}
// 1798 "scanner.c"
yy164:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy165;
			default:	goto yy98;
			}
yy165:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy166;
			default:	goto yy98;
			}
yy166:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy167;
			}
yy167:
// 172 "scanner.re"
			{
			s->active_char += sizeof("boolean")-1;
			token->opcode = XX_T_TYPE_BOOL;
			return 0;
		}
// 1889 "scanner.c"
yy168:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy175;
			default:	goto yy98;
			}
yy169:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy170;
			default:	goto yy98;
			}
yy170:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy171;
			default:	goto yy98;
			}
yy171:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy172;
			default:	goto yy98;
			}
yy172:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy173;
			default:	goto yy98;
			}
yy173:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy174;
			}
yy174:
// 154 "scanner.re"
			{
			s->active_char += sizeof("double")-1;
			token->opcode = XX_T_TYPE_DOUBLE;
			return 0;
		}
// 2001 "scanner.c"
yy175:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy176;
			default:	goto yy98;
			}
yy176:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy177;
			default:	goto yy98;
			}
yy177:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy178;
			default:	goto yy98;
			}
yy178:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy179;
			default:	goto yy98;
			}
yy179:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy180;
			}
yy180:
// 298 "scanner.re"
			{
			token->opcode = XX_T_DEFAULT;
			s->active_char += sizeof("default")-1;
			return 0;
		}
// 2106 "scanner.c"
yy181:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy182;
			}
yy182:
// 190 "scanner.re"
			{
			s->active_char += sizeof("if")-1;
			token->opcode = XX_T_IF;
			return 0;
		}
// 2183 "scanner.c"
yy183:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			case 'S':
			case 's':	goto yy192;
			case 'T':
			case 't':	goto yy190;
			default:	goto yy184;
			}
yy184:
// 214 "scanner.re"
			{
			s->active_char += sizeof("in")-1;
			token->opcode = XX_T_IN;
			return 0;
		}
// 2260 "scanner.c"
yy185:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy186;
			default:	goto yy98;
			}
yy186:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy187;
			default:	goto yy98;
			}
yy187:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy188;
			default:	goto yy98;
			}
yy188:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy189;
			}
yy189:
// 262 "scanner.re"
			{
			token->opcode = XX_T_ISSET;
			s->active_char += sizeof("isset")-1;
			return 0;
		}
// 2358 "scanner.c"
yy190:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy191;
			}
yy191:
// 142 "scanner.re"
			{
			s->active_char += sizeof("int")-1;
			token->opcode = XX_T_TYPE_INTEGER;
			return 0;
		}
// 2435 "scanner.c"
yy192:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy193;
			default:	goto yy98;
			}
yy193:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy194;
			default:	goto yy98;
			}
yy194:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy195;
			default:	goto yy98;
			}
yy195:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy196;
			default:	goto yy98;
			}
yy196:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy197;
			default:	goto yy98;
			}
yy197:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy198;
			default:	goto yy98;
			}
yy198:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy199;
			default:	goto yy98;
			}
yy199:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy200;
			}
yy200:
// 256 "scanner.re"
			{
			token->opcode = XX_T_INSTANCEOF;
			s->active_char += sizeof("instanceof")-1;
			return 0;
		}
// 2561 "scanner.c"
yy201:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy209;
			default:	goto yy98;
			}
yy202:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy203;
			case 'O':
			case 'o':	goto yy204;
			default:	goto yy98;
			}
yy203:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy207;
			default:	goto yy98;
			}
yy204:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy205;
			default:	goto yy98;
			}
yy205:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy206;
			}
yy206:
// 232 "scanner.re"
			{
			token->opcode = XX_T_LOOP;
			s->active_char += sizeof("loop")-1;
			return 0;
		}
// 2668 "scanner.c"
yy207:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy208;
			}
yy208:
// 148 "scanner.re"
			{
			s->active_char += sizeof("long")-1;
			token->opcode = XX_T_TYPE_INTEGER;
			return 0;
		}
// 2745 "scanner.c"
yy209:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy210;
			}
yy210:
// 124 "scanner.re"
			{
			s->active_char += sizeof("let")-1;
			token->opcode = XX_T_LET;
			return 0;
		}
// 2822 "scanner.c"
yy211:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy218;
			default:	goto yy98;
			}
yy212:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy213;
			default:	goto yy98;
			}
yy213:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy214;
			default:	goto yy98;
			}
yy214:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy215;
			default:	goto yy98;
			}
yy215:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy216;
			default:	goto yy98;
			}
yy216:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy217;
			}
yy217:
// 100 "scanner.re"
			{
			s->active_char += sizeof("public")-1;
			token->opcode = XX_T_PUBLIC;
			return 0;
		}
// 2934 "scanner.c"
yy218:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy219;
			default:	goto yy98;
			}
yy219:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy220;
			default:	goto yy98;
			}
yy220:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy221;
			default:	goto yy98;
			}
yy221:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy222;
			default:	goto yy98;
			}
yy222:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy223;
			default:	goto yy98;
			}
yy223:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy224;
			default:	goto yy98;
			}
yy224:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy225;
			}
yy225:
// 106 "scanner.re"
			{
			s->active_char += sizeof("protected")-1;
			token->opcode = XX_T_PROTECTED;
			return 0;
		}
// 3053 "scanner.c"
yy226:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy238;
			default:	goto yy98;
			}
yy227:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy235;
			default:	goto yy98;
			}
yy228:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy229;
			default:	goto yy98;
			}
yy229:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy230;
			default:	goto yy98;
			}
yy230:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy231;
			default:	goto yy98;
			}
yy231:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy232;
			default:	goto yy98;
			}
yy232:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy233;
			default:	goto yy98;
			}
yy233:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy234;
			}
yy234:
// 94 "scanner.re"
			{
			s->active_char += sizeof("extends")-1;
			token->opcode = XX_T_EXTENDS;
			return 0;
		}
// 3179 "scanner.c"
yy235:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy236;
			default:	goto yy98;
			}
yy236:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy237;
			}
yy237:
// 196 "scanner.re"
			{
			s->active_char += sizeof("else")-1;
			token->opcode = XX_T_ELSE;
			return 0;
		}
// 3263 "scanner.c"
yy238:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy239;
			default:	goto yy98;
			}
yy239:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy240;
			}
yy240:
// 130 "scanner.re"
			{
			s->active_char += sizeof("echo")-1;
			token->opcode = XX_T_ECHO;
			return 0;
		}
// 3347 "scanner.c"
yy241:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy258;
			default:	goto yy98;
			}
yy242:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy254;
			default:	goto yy98;
			}
yy243:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy244;
			default:	goto yy98;
			}
yy244:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy245;
			case 'T':
			case 't':	goto yy246;
			default:	goto yy98;
			}
yy245:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy252;
			default:	goto yy98;
			}
yy246:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy247;
			default:	goto yy98;
			}
yy247:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy248;
			default:	goto yy98;
			}
yy248:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy249;
			default:	goto yy98;
			}
yy249:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy250;
			default:	goto yy98;
			}
yy250:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy251;
			}
yy251:
// 244 "scanner.re"
			{
			token->opcode = XX_T_CONTINUE;
			s->active_char += sizeof("continue")-1;
			return 0;
		}
// 3489 "scanner.c"
yy252:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy253;
			}
yy253:
// 136 "scanner.re"
			{
			s->active_char += sizeof("const")-1;
			token->opcode = XX_T_CONST;
			return 0;
		}
// 3566 "scanner.c"
yy254:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy255;
			default:	goto yy98;
			}
yy255:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy256;
			default:	goto yy98;
			}
yy256:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy257;
			}
yy257:
// 88 "scanner.re"
			{
			s->active_char += sizeof("class")-1;
			token->opcode = XX_T_CLASS;
			return 0;
		}
// 3657 "scanner.c"
yy258:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy259;
			default:	goto yy98;
			}
yy259:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy260;
			}
yy260:
// 292 "scanner.re"
			{
			token->opcode = XX_T_CASE;
			s->active_char += sizeof("case")-1;
			return 0;
		}
// 3741 "scanner.c"
yy261:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy262;
			default:	goto yy98;
			}
yy262:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy263;
			default:	goto yy98;
			}
yy263:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy264;
			default:	goto yy98;
			}
yy264:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy265;
			default:	goto yy98;
			}
yy265:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy266;
			default:	goto yy98;
			}
yy266:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy267;
			default:	goto yy98;
			}
yy267:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy268;
			}
yy268:
// 82 "scanner.re"
			{
			s->active_char += sizeof("abstract")-1;
			token->opcode = XX_T_ABSTRACT;
			return 0;
		}
// 3860 "scanner.c"
yy269:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy280;
			default:	goto yy98;
			}
yy270:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy277;
			default:	goto yy98;
			}
yy271:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy272;
			default:	goto yy98;
			}
yy272:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy273;
			default:	goto yy98;
			}
yy273:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy274;
			default:	goto yy98;
			}
yy274:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy275;
			default:	goto yy98;
			}
yy275:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy276;
			}
yy276:
// 250 "scanner.re"
			{
			token->opcode = XX_T_TYPEOF;
			s->active_char += sizeof("typeof")-1;
			return 0;
		}
// 3979 "scanner.c"
yy277:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy278;
			default:	goto yy98;
			}
yy278:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy279;
			}
yy279:
// 70 "scanner.re"
			{
			s->active_char += sizeof("true")-1;
			token->opcode = XX_T_TRUE;
			return 0;
		}
// 4063 "scanner.c"
yy280:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy281;
			default:	goto yy98;
			}
yy281:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'W':
			case 'w':	goto yy282;
			default:	goto yy98;
			}
yy282:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy283;
			}
yy283:
// 274 "scanner.re"
			{
			token->opcode = XX_T_THROW;
			s->active_char += sizeof("throw")-1;
			return 0;
		}
// 4154 "scanner.c"
yy284:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy308;
			default:	goto yy98;
			}
yy285:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy304;
			default:	goto yy98;
			}
yy286:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy300;
			default:	goto yy98;
			}
yy287:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy288;
			}
yy288:
// 118 "scanner.re"
			{
			s->active_char += sizeof("fn")-1;
			token->opcode = XX_T_FUNCTION;
			return 0;
		}
// 4252 "scanner.c"
yy289:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy298;
			default:	goto yy98;
			}
yy290:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy291;
			default:	goto yy98;
			}
yy291:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy292;
			default:	goto yy98;
			}
yy292:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy293;
			default:	goto yy98;
			}
yy293:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy294;
			default:	goto yy98;
			}
yy294:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy295;
			default:	goto yy98;
			}
yy295:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy296;
			default:	goto yy98;
			}
yy296:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy297;
			}
yy297:
// 112 "scanner.re"
			{
			s->active_char += sizeof("function")-1;
			token->opcode = XX_T_FUNCTION;
			return 0;
		}
// 4378 "scanner.c"
yy298:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy299;
			}
yy299:
// 208 "scanner.re"
			{
			s->active_char += sizeof("for")-1;
			token->opcode = XX_T_FOR;
			return 0;
		}
// 4455 "scanner.c"
yy300:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy301;
			default:	goto yy98;
			}
yy301:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy302;
			default:	goto yy98;
			}
yy302:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy303;
			}
yy303:
// 160 "scanner.re"
			{
			s->active_char += sizeof("float")-1;
			token->opcode = XX_T_TYPE_DOUBLE;
			return 0;
		}
// 4546 "scanner.c"
yy304:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy305;
			default:	goto yy98;
			}
yy305:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy306;
			default:	goto yy98;
			}
yy306:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy307;
			}
yy307:
// 280 "scanner.re"
			{
			token->opcode = XX_T_FETCH;
			s->active_char += sizeof("fetch")-1;
			return 0;
		}
// 4637 "scanner.c"
yy308:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy309;
			default:	goto yy98;
			}
yy309:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy310;
			default:	goto yy98;
			}
yy310:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy311;
			}
yy311:
// 64 "scanner.re"
			{
			s->active_char += sizeof("false")-1;
			token->opcode = XX_T_FALSE;
			return 0;
		}
// 4728 "scanner.c"
yy312:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy320;
			default:	goto yy98;
			}
yy313:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'W':
			case 'w':	goto yy318;
			default:	goto yy98;
			}
yy314:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy315;
			default:	goto yy98;
			}
yy315:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy316;
			default:	goto yy98;
			}
yy316:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy317;
			}
yy317:
// 58 "scanner.re"
			{
			s->active_char += sizeof("null")-1;
			token->opcode = XX_T_NULL;
			return 0;
		}
// 4833 "scanner.c"
yy318:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy319;
			}
yy319:
// 220 "scanner.re"
			{
			s->active_char += sizeof("new")-1;
			token->opcode = XX_T_NEW;
			return 0;
		}
// 4910 "scanner.c"
yy320:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy321;
			default:	goto yy98;
			}
yy321:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy322;
			default:	goto yy98;
			}
yy322:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy323;
			default:	goto yy98;
			}
yy323:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy324;
			default:	goto yy98;
			}
yy324:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy325;
			default:	goto yy98;
			}
yy325:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy326;
			default:	goto yy98;
			}
yy326:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy327;
			}
yy327:
// 76 "scanner.re"
			{
			s->active_char += sizeof("namespace")-1;
			token->opcode = XX_T_NAMESPACE;
			return 0;
		}
// 5029 "scanner.c"
yy328:
			yych = *++YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy331;
			default:	goto yy111;
			}
yy329:
			yyaccept = 0;
			YYMARKER = ++YYCURSOR;
			yych = *YYCURSOR;
yy330:
			switch (yych) {
			case '.':	goto yy328;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy329;
			default:	goto yy5;
			}
yy331:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy331;
			default:	goto yy333;
			}
yy333:
// 49 "scanner.re"
			{
			token->opcode = XX_T_DOUBLE;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 5090 "scanner.c"
yy334:
			++YYCURSOR;
// 525 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_DECR;
			return 0;
		}
// 5099 "scanner.c"
yy336:
			++YYCURSOR;
// 495 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_ARROW;
			return 0;
		}
// 5108 "scanner.c"
yy338:
			++YYCURSOR;
// 423 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SUBASSIGN;
			return 0;
		}
// 5117 "scanner.c"
		}
// 572 "scanner.re"

	}

	return status;
}
