/* Generated by re2c 0.13.5 on Wed Jul 17 10:28:17 2013 */
// 1 "scanner.re"


#include "string.h"
#include "scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int xx_get_token(xx_scanner_state *s, xx_scanner_token *token) {

	char next, *q = YYCURSOR, *start = YYCURSOR;
	int status = XX_SCANNER_RETCODE_IMPOSSIBLE;

	while (XX_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
// 22 "scanner.c"
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy44;
			case '\t':
			case '\r':
			case ' ':	goto yy40;
			case '\n':	goto yy42;
			case '"':	goto yy14;
			case '\'':	goto yy15;
			case '(':	goto yy18;
			case ')':	goto yy20;
			case ',':	goto yy38;
			case '-':	goto yy2;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy4;
			case ':':	goto yy34;
			case ';':	goto yy36;
			case '=':	goto yy32;
			case '@':	goto yy30;
			case 'A':
			case 'B':
			case 'D':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'M':
			case 'O':
			case 'Q':
			case 'R':
			case 'S':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'b':
			case 'd':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'm':
			case 'o':
			case 'q':
			case 'r':
			case 's':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy17;
			case 'C':
			case 'c':	goto yy10;
			case 'E':
			case 'e':	goto yy11;
			case 'F':
			case 'f':	goto yy8;
			case 'L':
			case 'l':	goto yy13;
			case 'N':
			case 'n':	goto yy6;
			case 'P':
			case 'p':	goto yy12;
			case 'T':
			case 't':	goto yy9;
			case '[':	goto yy26;
			case '\\':
			case '_':	goto yy16;
			case ']':	goto yy28;
			case '{':	goto yy22;
			case '}':	goto yy24;
			default:	goto yy46;
			}
yy2:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy123;
			default:	goto yy3;
			}
yy3:
// 184 "scanner.re"
			{
			status = XX_SCANNER_RETCODE_ERR;
			break;
		}
// 135 "scanner.c"
yy4:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			goto yy124;
yy5:
// 23 "scanner.re"
			{
			token->opcode = XX_T_INTEGER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			q = YYCURSOR;
			return 0;
		}
// 149 "scanner.c"
yy6:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case 'A':
			case 'a':	goto yy109;
			case 'U':
			case 'u':	goto yy110;
			default:	goto yy50;
			}
yy7:
// 105 "scanner.re"
			{
			token->opcode = XX_T_IDENTIFIER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			q = YYCURSOR;
			return 0;
		}
// 168 "scanner.c"
yy8:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy94;
			case 'N':
			case 'n':	goto yy95;
			case 'U':
			case 'u':	goto yy97;
			default:	goto yy50;
			}
yy9:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy90;
			default:	goto yy50;
			}
yy10:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy85;
			default:	goto yy50;
			}
yy11:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'X':
			case 'x':	goto yy78;
			default:	goto yy50;
			}
yy12:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy63;
			case 'U':
			case 'u':	goto yy64;
			default:	goto yy50;
			}
yy13:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy60;
			default:	goto yy50;
			}
yy14:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy3;
			goto yy58;
yy15:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy3;
			goto yy52;
yy16:
			yych = *++YYCURSOR;
			goto yy50;
yy17:
			yych = *++YYCURSOR;
			goto yy50;
yy18:
			++YYCURSOR;
// 113 "scanner.re"
			{
			token->opcode = XX_T_PARENTHESES_OPEN;
			return 0;
		}
// 240 "scanner.c"
yy20:
			++YYCURSOR;
// 118 "scanner.re"
			{
			token->opcode = XX_T_PARENTHESES_CLOSE;
			return 0;
		}
// 248 "scanner.c"
yy22:
			++YYCURSOR;
// 123 "scanner.re"
			{
			token->opcode = XX_T_BRACKET_OPEN;
			return 0;
		}
// 256 "scanner.c"
yy24:
			++YYCURSOR;
// 128 "scanner.re"
			{
			token->opcode = XX_T_BRACKET_CLOSE;
			return 0;
		}
// 264 "scanner.c"
yy26:
			++YYCURSOR;
// 133 "scanner.re"
			{
			token->opcode = XX_T_SBRACKET_OPEN;
			return 0;
		}
// 272 "scanner.c"
yy28:
			++YYCURSOR;
// 138 "scanner.re"
			{
			token->opcode = XX_T_SBRACKET_CLOSE;
			return 0;
		}
// 280 "scanner.c"
yy30:
			++YYCURSOR;
// 143 "scanner.re"
			{
			token->opcode = XX_T_AT;
			return 0;
		}
// 288 "scanner.c"
yy32:
			++YYCURSOR;
// 148 "scanner.re"
			{
			token->opcode = XX_T_ASSIGN;
			return 0;
		}
// 296 "scanner.c"
yy34:
			++YYCURSOR;
// 153 "scanner.re"
			{
			token->opcode = XX_T_COLON;
			return 0;
		}
// 304 "scanner.c"
yy36:
			++YYCURSOR;
// 158 "scanner.re"
			{
			token->opcode = XX_T_DOTCOMMA;
			return 0;
		}
// 312 "scanner.c"
yy38:
			++YYCURSOR;
// 163 "scanner.re"
			{
			token->opcode = XX_T_COMMA;
			return 0;
		}
// 320 "scanner.c"
yy40:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy48;
yy41:
// 168 "scanner.re"
			{
			token->opcode = XX_T_IGNORE;
			return 0;
		}
// 331 "scanner.c"
yy42:
			++YYCURSOR;
// 173 "scanner.re"
			{
			s->active_line++;
			token->opcode = XX_T_IGNORE;
			return 0;
		}
// 340 "scanner.c"
yy44:
			++YYCURSOR;
// 179 "scanner.re"
			{
			status = XX_SCANNER_RETCODE_EOF;
			break;
		}
// 348 "scanner.c"
yy46:
			yych = *++YYCURSOR;
			goto yy3;
yy47:
			++YYCURSOR;
			yych = *YYCURSOR;
yy48:
			switch (yych) {
			case '\t':
			case '\r':
			case ' ':	goto yy47;
			default:	goto yy41;
			}
yy49:
			++YYCURSOR;
			yych = *YYCURSOR;
yy50:
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy7;
			}
yy51:
			++YYCURSOR;
			yych = *YYCURSOR;
yy52:
			switch (yych) {
			case 0x00:	goto yy53;
			case '\'':	goto yy55;
			case '\\':	goto yy54;
			default:	goto yy51;
			}
yy53:
			YYCURSOR = YYMARKER;
			switch (yyaccept) {
			case 0: 	goto yy5;
			case 1: 	goto yy3;
			}
yy54:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy53;
			default:	goto yy51;
			}
yy55:
			++YYCURSOR;
// 96 "scanner.re"
			{
			token->opcode = XX_T_STRING;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
// 466 "scanner.c"
yy57:
			++YYCURSOR;
			yych = *YYCURSOR;
yy58:
			switch (yych) {
			case 0x00:	goto yy53;
			case '"':	goto yy55;
			case '\\':	goto yy59;
			default:	goto yy57;
			}
yy59:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy53;
			default:	goto yy57;
			}
yy60:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy61;
			default:	goto yy50;
			}
yy61:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy62;
			}
yy62:
// 90 "scanner.re"
			{
			token->opcode = XX_T_LET;
			return 0;
		}
// 566 "scanner.c"
yy63:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy70;
			default:	goto yy50;
			}
yy64:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy65;
			default:	goto yy50;
			}
yy65:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy66;
			default:	goto yy50;
			}
yy66:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy67;
			default:	goto yy50;
			}
yy67:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy68;
			default:	goto yy50;
			}
yy68:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy69;
			}
yy69:
// 70 "scanner.re"
			{
			token->opcode = XX_T_PUBLIC;
			return 0;
		}
// 677 "scanner.c"
yy70:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy71;
			default:	goto yy50;
			}
yy71:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy72;
			default:	goto yy50;
			}
yy72:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy73;
			default:	goto yy50;
			}
yy73:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy74;
			default:	goto yy50;
			}
yy74:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy75;
			default:	goto yy50;
			}
yy75:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy76;
			default:	goto yy50;
			}
yy76:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy77;
			}
yy77:
// 75 "scanner.re"
			{
			token->opcode = XX_T_PROTECTED;
			return 0;
		}
// 795 "scanner.c"
yy78:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy79;
			default:	goto yy50;
			}
yy79:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy80;
			default:	goto yy50;
			}
yy80:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy81;
			default:	goto yy50;
			}
yy81:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy82;
			default:	goto yy50;
			}
yy82:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy83;
			default:	goto yy50;
			}
yy83:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy84;
			}
yy84:
// 65 "scanner.re"
			{
			token->opcode = XX_T_EXTENDS;
			return 0;
		}
// 906 "scanner.c"
yy85:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy86;
			default:	goto yy50;
			}
yy86:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy87;
			default:	goto yy50;
			}
yy87:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy88;
			default:	goto yy50;
			}
yy88:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy89;
			}
yy89:
// 60 "scanner.re"
			{
			token->opcode = XX_T_CLASS;
			return 0;
		}
// 1003 "scanner.c"
yy90:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy91;
			default:	goto yy50;
			}
yy91:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy92;
			default:	goto yy50;
			}
yy92:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy93;
			}
yy93:
// 50 "scanner.re"
			{
			token->opcode = XX_T_TRUE;
			return 0;
		}
// 1093 "scanner.c"
yy94:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy105;
			default:	goto yy50;
			}
yy95:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy96;
			}
yy96:
// 85 "scanner.re"
			{
			token->opcode = XX_T_FUNCTION;
			return 0;
		}
// 1176 "scanner.c"
yy97:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy98;
			default:	goto yy50;
			}
yy98:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy99;
			default:	goto yy50;
			}
yy99:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy100;
			default:	goto yy50;
			}
yy100:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy101;
			default:	goto yy50;
			}
yy101:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy102;
			default:	goto yy50;
			}
yy102:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy103;
			default:	goto yy50;
			}
yy103:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy104;
			}
yy104:
// 80 "scanner.re"
			{
			token->opcode = XX_T_FUNCTION;
			return 0;
		}
// 1294 "scanner.c"
yy105:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy106;
			default:	goto yy50;
			}
yy106:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy107;
			default:	goto yy50;
			}
yy107:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy108;
			}
yy108:
// 45 "scanner.re"
			{
			token->opcode = XX_T_FALSE;
			return 0;
		}
// 1384 "scanner.c"
yy109:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy114;
			default:	goto yy50;
			}
yy110:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy111;
			default:	goto yy50;
			}
yy111:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy112;
			default:	goto yy50;
			}
yy112:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy113;
			}
yy113:
// 40 "scanner.re"
			{
			token->opcode = XX_T_NULL;
			return 0;
		}
// 1481 "scanner.c"
yy114:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy115;
			default:	goto yy50;
			}
yy115:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy116;
			default:	goto yy50;
			}
yy116:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy117;
			default:	goto yy50;
			}
yy117:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy118;
			default:	goto yy50;
			}
yy118:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy119;
			default:	goto yy50;
			}
yy119:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy120;
			default:	goto yy50;
			}
yy120:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy49;
			default:	goto yy121;
			}
yy121:
// 55 "scanner.re"
			{
			token->opcode = XX_T_NAMESPACE;
			return 0;
		}
// 1599 "scanner.c"
yy122:
			yych = *++YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy125;
			default:	goto yy53;
			}
yy123:
			yyaccept = 0;
			YYMARKER = ++YYCURSOR;
			yych = *YYCURSOR;
yy124:
			switch (yych) {
			case '.':	goto yy122;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy123;
			default:	goto yy5;
			}
yy125:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy125;
			default:	goto yy127;
			}
yy127:
// 32 "scanner.re"
			{
			token->opcode = XX_T_DOUBLE;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			q = YYCURSOR;
			return 0;
		}
// 1659 "scanner.c"
		}
// 189 "scanner.re"

	}

	return status;
}
