/* Generated by re2c 0.13.5 on Tue Jul 30 18:05:13 2013 */
// 1 "scanner.re"

/*
 +----------------------------------------------------------------------+
 | Zephir Language                                                      |
 +----------------------------------------------------------------------+
 | Copyright (c) 2013 Zephir Team                                       |
 +----------------------------------------------------------------------+
 | This source file is subject to version 1.0 of the Zephir license,    |
 | that is bundled with this package in the file LICENSE, and is        |
 | available through the world-wide-web at the following url:           |
 | http://www.zephir-lang.com/license                                   |
 | If you did not receive a copy of the Zephir license and are unable   |
 | to obtain it through the world-wide-web, please send a note to       |
 | license@zephir-lang.com so we can mail you a copy immediately.       |
 +----------------------------------------------------------------------+
*/

#include "string.h"
#include "scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int xx_get_token(xx_scanner_state *s, xx_scanner_token *token) {

	char next, *q = YYCURSOR, *start = YYCURSOR;
	int status = XX_SCANNER_RETCODE_IMPOSSIBLE;

	while (XX_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
// 37 "scanner.c"
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy65;
			case '\t':
			case '\r':
			case ' ':	goto yy61;
			case '\n':	goto yy63;
			case '!':	goto yy43;
			case '"':	goto yy23;
			case '\'':	goto yy25;
			case '(':	goto yy29;
			case ')':	goto yy31;
			case '+':	goto yy53;
			case ',':	goto yy59;
			case '-':	goto yy2;
			case '.':	goto yy51;
			case '/':	goto yy26;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy4;
			case ':':	goto yy55;
			case ';':	goto yy57;
			case '<':	goto yy47;
			case '=':	goto yy45;
			case '>':	goto yy49;
			case '@':	goto yy41;
			case 'A':
			case 'a':	goto yy10;
			case 'B':
			case 'b':	goto yy17;
			case 'C':
			case 'c':	goto yy11;
			case 'D':
			case 'd':	goto yy16;
			case 'E':
			case 'e':	goto yy12;
			case 'F':
			case 'f':	goto yy8;
			case 'G':
			case 'H':
			case 'J':
			case 'K':
			case 'M':
			case 'O':
			case 'Q':
			case 'X':
			case 'Y':
			case 'Z':
			case 'g':
			case 'h':
			case 'j':
			case 'k':
			case 'm':
			case 'o':
			case 'q':
			case 'x':
			case 'y':
			case 'z':	goto yy28;
			case 'I':
			case 'i':	goto yy15;
			case 'L':
			case 'l':	goto yy14;
			case 'N':
			case 'n':	goto yy6;
			case 'P':
			case 'p':	goto yy13;
			case 'R':
			case 'r':	goto yy21;
			case 'S':
			case 's':	goto yy18;
			case 'T':
			case 't':	goto yy9;
			case 'U':
			case 'u':	goto yy22;
			case 'V':
			case 'v':	goto yy19;
			case 'W':
			case 'w':	goto yy20;
			case '[':	goto yy37;
			case '\\':
			case '_':	goto yy27;
			case ']':	goto yy39;
			case '{':	goto yy33;
			case '}':	goto yy35;
			default:	goto yy67;
			}
yy2:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '-':	goto yy287;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy282;
			case '>':	goto yy289;
			default:	goto yy3;
			}
yy3:
// 428 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SUB;
			return 0;
		}
// 159 "scanner.c"
yy4:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			goto yy283;
yy5:
// 38 "scanner.re"
			{
			token->opcode = XX_T_INTEGER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 174 "scanner.c"
yy6:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case 'A':
			case 'a':	goto yy265;
			case 'E':
			case 'e':	goto yy266;
			case 'U':
			case 'u':	goto yy267;
			default:	goto yy81;
			}
yy7:
// 311 "scanner.re"
			{
			token->opcode = XX_T_IDENTIFIER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 196 "scanner.c"
yy8:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy242;
			case 'L':
			case 'l':	goto yy243;
			case 'N':
			case 'n':	goto yy244;
			case 'O':
			case 'o':	goto yy246;
			case 'U':
			case 'u':	goto yy247;
			default:	goto yy81;
			}
yy9:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy227;
			case 'R':
			case 'r':	goto yy228;
			case 'Y':
			case 'y':	goto yy229;
			default:	goto yy81;
			}
yy10:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy219;
			default:	goto yy81;
			}
yy11:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy203;
			case 'O':
			case 'o':	goto yy204;
			default:	goto yy81;
			}
yy12:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy188;
			case 'L':
			case 'l':	goto yy189;
			case 'X':
			case 'x':	goto yy190;
			default:	goto yy81;
			}
yy13:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy173;
			case 'U':
			case 'u':	goto yy174;
			default:	goto yy81;
			}
yy14:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy163;
			case 'O':
			case 'o':	goto yy164;
			default:	goto yy81;
			}
yy15:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy143;
			case 'N':
			case 'n':	goto yy145;
			case 'S':
			case 's':	goto yy147;
			default:	goto yy81;
			}
yy16:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy137;
			default:	goto yy81;
			}
yy17:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy124;
			case 'R':
			case 'r':	goto yy125;
			default:	goto yy81;
			}
yy18:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy118;
			default:	goto yy81;
			}
yy19:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy115;
			default:	goto yy81;
			}
yy20:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy110;
			default:	goto yy81;
			}
yy21:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy104;
			default:	goto yy81;
			}
yy22:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy99;
			default:	goto yy81;
			}
yy23:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych >= 0x01) goto yy97;
yy24:
// 482 "scanner.re"
			{
			status = XX_SCANNER_RETCODE_ERR;
			break;
		}
// 340 "scanner.c"
yy25:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy24;
			goto yy91;
yy26:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case '*':	goto yy85;
			case '/':	goto yy82;
			default:	goto yy24;
			}
yy27:
			yych = *++YYCURSOR;
			goto yy81;
yy28:
			yych = *++YYCURSOR;
			goto yy81;
yy29:
			++YYCURSOR;
// 320 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_PARENTHESES_OPEN;
			return 0;
		}
// 368 "scanner.c"
yy31:
			++YYCURSOR;
// 326 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_PARENTHESES_CLOSE;
			return 0;
		}
// 377 "scanner.c"
yy33:
			++YYCURSOR;
// 332 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_BRACKET_OPEN;
			return 0;
		}
// 386 "scanner.c"
yy35:
			++YYCURSOR;
// 338 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_BRACKET_CLOSE;
			return 0;
		}
// 395 "scanner.c"
yy37:
			++YYCURSOR;
// 344 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SBRACKET_OPEN;
			return 0;
		}
// 404 "scanner.c"
yy39:
			++YYCURSOR;
// 350 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SBRACKET_CLOSE;
			return 0;
		}
// 413 "scanner.c"
yy41:
			++YYCURSOR;
// 356 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_AT;
			return 0;
		}
// 422 "scanner.c"
yy43:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy76;
			default:	goto yy44;
			}
yy44:
// 362 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_NOT;
			return 0;
		}
// 436 "scanner.c"
yy45:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy72;
			default:	goto yy46;
			}
yy46:
// 368 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_ASSIGN;
			return 0;
		}
// 450 "scanner.c"
yy47:
			++YYCURSOR;
// 398 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_LESS;
			return 0;
		}
// 459 "scanner.c"
yy49:
			++YYCURSOR;
// 404 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_GREATER;
			return 0;
		}
// 468 "scanner.c"
yy51:
			++YYCURSOR;
// 416 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_DOT;
			return 0;
		}
// 477 "scanner.c"
yy53:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '+':	goto yy70;
			default:	goto yy54;
			}
yy54:
// 422 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_ADD;
			return 0;
		}
// 491 "scanner.c"
yy55:
			++YYCURSOR;
// 446 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_COLON;
			return 0;
		}
// 500 "scanner.c"
yy57:
			++YYCURSOR;
// 452 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_DOTCOMMA;
			return 0;
		}
// 509 "scanner.c"
yy59:
			++YYCURSOR;
// 458 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_COMMA;
			return 0;
		}
// 518 "scanner.c"
yy61:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy69;
yy62:
// 464 "scanner.re"
			{
			s->active_char += (YYCURSOR - start);
			token->opcode = XX_T_IGNORE;
			return 0;
		}
// 530 "scanner.c"
yy63:
			++YYCURSOR;
// 470 "scanner.re"
			{
			s->active_line++;
			s->active_char = 0;
			token->opcode = XX_T_IGNORE;
			return 0;
		}
// 540 "scanner.c"
yy65:
			++YYCURSOR;
// 477 "scanner.re"
			{
			status = XX_SCANNER_RETCODE_EOF;
			break;
		}
// 548 "scanner.c"
yy67:
			yych = *++YYCURSOR;
			goto yy24;
yy68:
			++YYCURSOR;
			yych = *YYCURSOR;
yy69:
			switch (yych) {
			case '\t':
			case '\r':
			case ' ':	goto yy68;
			default:	goto yy62;
			}
yy70:
			++YYCURSOR;
// 434 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_INCR;
			return 0;
		}
// 570 "scanner.c"
yy72:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy74;
			default:	goto yy73;
			}
yy73:
// 374 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_EQUALS;
			return 0;
		}
// 584 "scanner.c"
yy74:
			++YYCURSOR;
// 386 "scanner.re"
			{
			s->active_char += 3;
			token->opcode = XX_T_IDENTICAL;
			return 0;
		}
// 593 "scanner.c"
yy76:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy78;
			default:	goto yy77;
			}
yy77:
// 380 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_NOTEQUALS;
			return 0;
		}
// 607 "scanner.c"
yy78:
			++YYCURSOR;
// 392 "scanner.re"
			{
			s->active_char += 3;
			token->opcode = XX_T_NOTIDENTICAL;
			return 0;
		}
// 616 "scanner.c"
yy80:
			++YYCURSOR;
			yych = *YYCURSOR;
yy81:
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy7;
			}
yy82:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':
			case '\r':	goto yy84;
			default:	goto yy82;
			}
yy84:
// 290 "scanner.re"
			{
			token->opcode = XX_T_COMMENT;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			{
				int k, ch = s->active_char;
				for (k = 0; k < (token->len - 1); k++) {
					if (token->value[k] == '\n') {
						ch = 1;
						s->active_line++;
					} else {
						ch++;
					}
				}
				s->active_char = ch;
			}
			q = YYCURSOR;
			return 0;
		}
// 717 "scanner.c"
yy85:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':	goto yy87;
			default:	goto yy85;
			}
yy87:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':	goto yy87;
			case '/':	goto yy89;
			default:	goto yy85;
			}
yy89:
			yych = *++YYCURSOR;
			goto yy84;
yy90:
			++YYCURSOR;
			yych = *YYCURSOR;
yy91:
			switch (yych) {
			case 0x00:	goto yy92;
			case '\'':	goto yy94;
			case '\\':	goto yy93;
			default:	goto yy90;
			}
yy92:
			YYCURSOR = YYMARKER;
			switch (yyaccept) {
			case 0: 	goto yy5;
			case 1: 	goto yy24;
			}
yy93:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy92;
			default:	goto yy90;
			}
yy94:
			++YYCURSOR;
// 280 "scanner.re"
			{
			token->opcode = XX_T_STRING;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 770 "scanner.c"
yy96:
			++YYCURSOR;
			yych = *YYCURSOR;
yy97:
			switch (yych) {
			case 0x00:	goto yy92;
			case '"':	goto yy94;
			case '\\':	goto yy98;
			default:	goto yy96;
			}
yy98:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy92;
			default:	goto yy96;
			}
yy99:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy100;
			default:	goto yy81;
			}
yy100:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy101;
			default:	goto yy81;
			}
yy101:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy102;
			default:	goto yy81;
			}
yy102:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy103;
			}
yy103:
// 267 "scanner.re"
			{
			token->opcode = XX_T_UNSET;
			s->active_char += sizeof("unset")-1;
			return 0;
		}
// 885 "scanner.c"
yy104:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy105;
			default:	goto yy81;
			}
yy105:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy106;
			default:	goto yy81;
			}
yy106:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy107;
			default:	goto yy81;
			}
yy107:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy108;
			default:	goto yy81;
			}
yy108:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy109;
			}
yy109:
// 225 "scanner.re"
			{
			s->active_char += sizeof("return")-1;
			token->opcode = XX_T_RETURN;
			return 0;
		}
// 990 "scanner.c"
yy110:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy111;
			default:	goto yy81;
			}
yy111:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy112;
			default:	goto yy81;
			}
yy112:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy113;
			default:	goto yy81;
			}
yy113:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy114;
			}
yy114:
// 201 "scanner.re"
			{
			s->active_char += sizeof("while")-1;
			token->opcode = XX_T_WHILE;
			return 0;
		}
// 1088 "scanner.c"
yy115:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy116;
			default:	goto yy81;
			}
yy116:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy117;
			}
yy117:
// 183 "scanner.re"
			{
			s->active_char += sizeof("var")-1;
			token->opcode = XX_T_TYPE_VAR;
			return 0;
		}
// 1172 "scanner.c"
yy118:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy119;
			default:	goto yy81;
			}
yy119:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy120;
			default:	goto yy81;
			}
yy120:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy121;
			default:	goto yy81;
			}
yy121:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy122;
			default:	goto yy81;
			}
yy122:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy123;
			}
yy123:
// 177 "scanner.re"
			{
			s->active_char += sizeof("string")-1;
			token->opcode = XX_T_TYPE_STRING;
			return 0;
		}
// 1277 "scanner.c"
yy124:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy130;
			default:	goto yy81;
			}
yy125:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy126;
			default:	goto yy81;
			}
yy126:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy127;
			default:	goto yy81;
			}
yy127:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'K':
			case 'k':	goto yy128;
			default:	goto yy81;
			}
yy128:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy129;
			}
yy129:
// 237 "scanner.re"
			{
			token->opcode = XX_T_BREAK;
			s->active_char += sizeof("break")-1;
			return 0;
		}
// 1382 "scanner.c"
yy130:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy131;
			default:	goto yy81;
			}
yy131:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			case 'E':
			case 'e':	goto yy133;
			default:	goto yy132;
			}
yy132:
// 165 "scanner.re"
			{
			s->active_char += sizeof("bool")-1;
			token->opcode = XX_T_TYPE_BOOL;
			return 0;
		}
// 1466 "scanner.c"
yy133:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy134;
			default:	goto yy81;
			}
yy134:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy135;
			default:	goto yy81;
			}
yy135:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy136;
			}
yy136:
// 171 "scanner.re"
			{
			s->active_char += sizeof("boolean")-1;
			token->opcode = XX_T_TYPE_BOOL;
			return 0;
		}
// 1557 "scanner.c"
yy137:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy138;
			default:	goto yy81;
			}
yy138:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy139;
			default:	goto yy81;
			}
yy139:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy140;
			default:	goto yy81;
			}
yy140:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy141;
			default:	goto yy81;
			}
yy141:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy142;
			}
yy142:
// 153 "scanner.re"
			{
			s->active_char += sizeof("double")-1;
			token->opcode = XX_T_TYPE_DOUBLE;
			return 0;
		}
// 1662 "scanner.c"
yy143:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy144;
			}
yy144:
// 189 "scanner.re"
			{
			s->active_char += sizeof("if")-1;
			token->opcode = XX_T_IF;
			return 0;
		}
// 1739 "scanner.c"
yy145:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			case 'S':
			case 's':	goto yy154;
			case 'T':
			case 't':	goto yy152;
			default:	goto yy146;
			}
yy146:
// 213 "scanner.re"
			{
			s->active_char += sizeof("in")-1;
			token->opcode = XX_T_IN;
			return 0;
		}
// 1816 "scanner.c"
yy147:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy148;
			default:	goto yy81;
			}
yy148:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy149;
			default:	goto yy81;
			}
yy149:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy150;
			default:	goto yy81;
			}
yy150:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy151;
			}
yy151:
// 261 "scanner.re"
			{
			token->opcode = XX_T_ISSET;
			s->active_char += sizeof("isset")-1;
			return 0;
		}
// 1914 "scanner.c"
yy152:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy153;
			}
yy153:
// 141 "scanner.re"
			{
			s->active_char += sizeof("int")-1;
			token->opcode = XX_T_TYPE_INTEGER;
			return 0;
		}
// 1991 "scanner.c"
yy154:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy155;
			default:	goto yy81;
			}
yy155:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy156;
			default:	goto yy81;
			}
yy156:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy157;
			default:	goto yy81;
			}
yy157:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy158;
			default:	goto yy81;
			}
yy158:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy159;
			default:	goto yy81;
			}
yy159:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy160;
			default:	goto yy81;
			}
yy160:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy161;
			default:	goto yy81;
			}
yy161:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy162;
			}
yy162:
// 255 "scanner.re"
			{
			token->opcode = XX_T_INSTANCEOF;
			s->active_char += sizeof("instanceof")-1;
			return 0;
		}
// 2117 "scanner.c"
yy163:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy171;
			default:	goto yy81;
			}
yy164:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy165;
			case 'O':
			case 'o':	goto yy166;
			default:	goto yy81;
			}
yy165:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy169;
			default:	goto yy81;
			}
yy166:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy167;
			default:	goto yy81;
			}
yy167:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy168;
			}
yy168:
// 231 "scanner.re"
			{
			token->opcode = XX_T_LOOP;
			s->active_char += sizeof("loop")-1;
			return 0;
		}
// 2224 "scanner.c"
yy169:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy170;
			}
yy170:
// 147 "scanner.re"
			{
			s->active_char += sizeof("long")-1;
			token->opcode = XX_T_TYPE_INTEGER;
			return 0;
		}
// 2301 "scanner.c"
yy171:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy172;
			}
yy172:
// 123 "scanner.re"
			{
			s->active_char += sizeof("let")-1;
			token->opcode = XX_T_LET;
			return 0;
		}
// 2378 "scanner.c"
yy173:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy180;
			default:	goto yy81;
			}
yy174:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy175;
			default:	goto yy81;
			}
yy175:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy176;
			default:	goto yy81;
			}
yy176:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy177;
			default:	goto yy81;
			}
yy177:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy178;
			default:	goto yy81;
			}
yy178:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy179;
			}
yy179:
// 99 "scanner.re"
			{
			s->active_char += sizeof("public")-1;
			token->opcode = XX_T_PUBLIC;
			return 0;
		}
// 2490 "scanner.c"
yy180:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy181;
			default:	goto yy81;
			}
yy181:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy182;
			default:	goto yy81;
			}
yy182:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy183;
			default:	goto yy81;
			}
yy183:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy184;
			default:	goto yy81;
			}
yy184:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy185;
			default:	goto yy81;
			}
yy185:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy186;
			default:	goto yy81;
			}
yy186:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy187;
			}
yy187:
// 105 "scanner.re"
			{
			s->active_char += sizeof("protected")-1;
			token->opcode = XX_T_PROTECTED;
			return 0;
		}
// 2609 "scanner.c"
yy188:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy200;
			default:	goto yy81;
			}
yy189:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy197;
			default:	goto yy81;
			}
yy190:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy191;
			default:	goto yy81;
			}
yy191:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy192;
			default:	goto yy81;
			}
yy192:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy193;
			default:	goto yy81;
			}
yy193:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy194;
			default:	goto yy81;
			}
yy194:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy195;
			default:	goto yy81;
			}
yy195:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy196;
			}
yy196:
// 93 "scanner.re"
			{
			s->active_char += sizeof("extends")-1;
			token->opcode = XX_T_EXTENDS;
			return 0;
		}
// 2735 "scanner.c"
yy197:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy198;
			default:	goto yy81;
			}
yy198:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy199;
			}
yy199:
// 195 "scanner.re"
			{
			s->active_char += sizeof("else")-1;
			token->opcode = XX_T_ELSE;
			return 0;
		}
// 2819 "scanner.c"
yy200:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy201;
			default:	goto yy81;
			}
yy201:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy202;
			}
yy202:
// 129 "scanner.re"
			{
			s->active_char += sizeof("echo")-1;
			token->opcode = XX_T_ECHO;
			return 0;
		}
// 2903 "scanner.c"
yy203:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy215;
			default:	goto yy81;
			}
yy204:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy205;
			default:	goto yy81;
			}
yy205:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy206;
			case 'T':
			case 't':	goto yy207;
			default:	goto yy81;
			}
yy206:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy213;
			default:	goto yy81;
			}
yy207:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy208;
			default:	goto yy81;
			}
yy208:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy209;
			default:	goto yy81;
			}
yy209:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy210;
			default:	goto yy81;
			}
yy210:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy211;
			default:	goto yy81;
			}
yy211:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy212;
			}
yy212:
// 243 "scanner.re"
			{
			token->opcode = XX_T_CONTINUE;
			s->active_char += sizeof("continue")-1;
			return 0;
		}
// 3038 "scanner.c"
yy213:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy214;
			}
yy214:
// 135 "scanner.re"
			{
			s->active_char += sizeof("const")-1;
			token->opcode = XX_T_CONST;
			return 0;
		}
// 3115 "scanner.c"
yy215:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy216;
			default:	goto yy81;
			}
yy216:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy217;
			default:	goto yy81;
			}
yy217:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy218;
			}
yy218:
// 87 "scanner.re"
			{
			s->active_char += sizeof("class")-1;
			token->opcode = XX_T_CLASS;
			return 0;
		}
// 3206 "scanner.c"
yy219:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy220;
			default:	goto yy81;
			}
yy220:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy221;
			default:	goto yy81;
			}
yy221:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy222;
			default:	goto yy81;
			}
yy222:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy223;
			default:	goto yy81;
			}
yy223:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy224;
			default:	goto yy81;
			}
yy224:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy225;
			default:	goto yy81;
			}
yy225:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy226;
			}
yy226:
// 81 "scanner.re"
			{
			s->active_char += sizeof("abstract")-1;
			token->opcode = XX_T_ABSTRACT;
			return 0;
		}
// 3325 "scanner.c"
yy227:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy238;
			default:	goto yy81;
			}
yy228:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy235;
			default:	goto yy81;
			}
yy229:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy230;
			default:	goto yy81;
			}
yy230:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy231;
			default:	goto yy81;
			}
yy231:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy232;
			default:	goto yy81;
			}
yy232:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy233;
			default:	goto yy81;
			}
yy233:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy234;
			}
yy234:
// 249 "scanner.re"
			{
			token->opcode = XX_T_TYPEOF;
			s->active_char += sizeof("typeof")-1;
			return 0;
		}
// 3444 "scanner.c"
yy235:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy236;
			default:	goto yy81;
			}
yy236:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy237;
			}
yy237:
// 69 "scanner.re"
			{
			s->active_char += sizeof("true")-1;
			token->opcode = XX_T_TRUE;
			return 0;
		}
// 3528 "scanner.c"
yy238:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy239;
			default:	goto yy81;
			}
yy239:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'W':
			case 'w':	goto yy240;
			default:	goto yy81;
			}
yy240:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy241;
			}
yy241:
// 273 "scanner.re"
			{
			token->opcode = XX_T_THROW;
			s->active_char += sizeof("throw")-1;
			return 0;
		}
// 3619 "scanner.c"
yy242:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy261;
			default:	goto yy81;
			}
yy243:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy257;
			default:	goto yy81;
			}
yy244:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy245;
			}
yy245:
// 117 "scanner.re"
			{
			s->active_char += sizeof("fn")-1;
			token->opcode = XX_T_FUNCTION;
			return 0;
		}
// 3710 "scanner.c"
yy246:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy255;
			default:	goto yy81;
			}
yy247:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy248;
			default:	goto yy81;
			}
yy248:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy249;
			default:	goto yy81;
			}
yy249:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy250;
			default:	goto yy81;
			}
yy250:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy251;
			default:	goto yy81;
			}
yy251:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy252;
			default:	goto yy81;
			}
yy252:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy253;
			default:	goto yy81;
			}
yy253:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy254;
			}
yy254:
// 111 "scanner.re"
			{
			s->active_char += sizeof("function")-1;
			token->opcode = XX_T_FUNCTION;
			return 0;
		}
// 3836 "scanner.c"
yy255:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy256;
			}
yy256:
// 207 "scanner.re"
			{
			s->active_char += sizeof("for")-1;
			token->opcode = XX_T_FOR;
			return 0;
		}
// 3913 "scanner.c"
yy257:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy258;
			default:	goto yy81;
			}
yy258:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy259;
			default:	goto yy81;
			}
yy259:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy260;
			}
yy260:
// 159 "scanner.re"
			{
			s->active_char += sizeof("float")-1;
			token->opcode = XX_T_TYPE_DOUBLE;
			return 0;
		}
// 4004 "scanner.c"
yy261:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy262;
			default:	goto yy81;
			}
yy262:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy263;
			default:	goto yy81;
			}
yy263:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy264;
			}
yy264:
// 63 "scanner.re"
			{
			s->active_char += sizeof("false")-1;
			token->opcode = XX_T_FALSE;
			return 0;
		}
// 4095 "scanner.c"
yy265:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy273;
			default:	goto yy81;
			}
yy266:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'W':
			case 'w':	goto yy271;
			default:	goto yy81;
			}
yy267:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy268;
			default:	goto yy81;
			}
yy268:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy269;
			default:	goto yy81;
			}
yy269:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy270;
			}
yy270:
// 57 "scanner.re"
			{
			s->active_char += sizeof("null")-1;
			token->opcode = XX_T_NULL;
			return 0;
		}
// 4200 "scanner.c"
yy271:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy272;
			}
yy272:
// 219 "scanner.re"
			{
			s->active_char += sizeof("new")-1;
			token->opcode = XX_T_NEW;
			return 0;
		}
// 4277 "scanner.c"
yy273:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy274;
			default:	goto yy81;
			}
yy274:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy275;
			default:	goto yy81;
			}
yy275:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy276;
			default:	goto yy81;
			}
yy276:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy277;
			default:	goto yy81;
			}
yy277:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy278;
			default:	goto yy81;
			}
yy278:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy279;
			default:	goto yy81;
			}
yy279:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy80;
			default:	goto yy280;
			}
yy280:
// 75 "scanner.re"
			{
			s->active_char += sizeof("namespace")-1;
			token->opcode = XX_T_NAMESPACE;
			return 0;
		}
// 4396 "scanner.c"
yy281:
			yych = *++YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy284;
			default:	goto yy92;
			}
yy282:
			yyaccept = 0;
			YYMARKER = ++YYCURSOR;
			yych = *YYCURSOR;
yy283:
			switch (yych) {
			case '.':	goto yy281;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy282;
			default:	goto yy5;
			}
yy284:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy284;
			default:	goto yy286;
			}
yy286:
// 48 "scanner.re"
			{
			token->opcode = XX_T_DOUBLE;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 4457 "scanner.c"
yy287:
			++YYCURSOR;
// 440 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_DECR;
			return 0;
		}
// 4466 "scanner.c"
yy289:
			++YYCURSOR;
// 410 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_ARROW;
			return 0;
		}
// 4475 "scanner.c"
		}
// 487 "scanner.re"

	}

	return status;
}
