#!/usr/bin/env php
<?php

/**
 * This file is part of the Zephir.
 *
 * (c) Phalcon Team <team@zephir-lang.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use Zephir\Console\Application;
use Zephir\DependencyInjection\ContainerFactory;

require __DIR__ . '/Library/autoload.php';
require __DIR__ . '/Library/bootstrap.php';

$container = (new ContainerFactory())->create();

$application = $container->get(Application::class);
$application->run();
