<html>


    <head>

        <?= $this->partial("partials/assets.phtml") ?>

        <script>var ZepCurrentPath = '<?=$this->url("/")?>'</script>

        <?= $this->partial("partials/analytics.phtml") ?>

    </head>


    <body onload="prettyPrint()">
        <div id="top-bar">
            <div id="top-left">
                <?php if ($this->themeOption("title")){ ?>
                    <?= str_replace( array("%_name_%", "%_version_%") , array($this->projectConfig("name"), $this->projectConfig('version')) , $this->themeOption("title")) ?>
                <?php }else{ ?>
                    <?= $this->projectConfig("name") ?> Documentation <span class="version">v<?php echo $this->projectConfig('version'); ?></span>
                <?php } ?>
            </div>
            <div id="top-right">

            </div>
        </div>

        <div id="body">

            <div id="body-left">

                <div class="header-search">

                    <input class="search-box" placeholder="Search for a class or namespace " type="text" />

                    <div id="menu-wrapper">


                    </div>

                </div>

            </div>
            <div id="body-right">
                <div class="content">
                    <?= $this->partial($contentPartial) ?>
                </div>
            </div>

        </div>

    </body>



</html>
