
extern zend_class_entry *test_properties_staticpropertyarray_ce;

ZEPHIR_INIT_CLASS(Test_Properties_StaticPropertyArray);

void zephir_init_static_properties_Test_Properties_StaticPropertyArray(TSRMLS_D);

ZEPHIR_INIT_FUNCS(test_properties_staticpropertyarray_method_entry) {
	PHP_FE_END
};
