#define ZEPHIR_PUBLIC                          1
#define ZEPHIR_PROTECTED                       2
#define ZEPHIR_STATIC                          3
#define ZEPHIR_PRIVATE                         4
#define ZEPHIR_SCOPED                          5
#define ZEPHIR_COMMA                           6
#define ZEPHIR_REQUIRE                         7
#define ZEPHIR_QUESTION                        8
#define ZEPHIR_LIKELY                          9
#define ZEPHIR_UNLIKELY                       10
#define ZEPHIR_INSTANCEOF                     11
#define ZEPHIR_OR                             12
#define ZEPHIR_AND                            13
#define ZEPHIR_BITWISE_OR                     14
#define ZEPHIR_BITWISE_AND                    15
#define ZEPHIR_BITWISE_XOR                    16
#define ZEPHIR_BITWISE_SHIFTLEFT              17
#define ZEPHIR_BITWISE_SHIFTRIGHT             18
#define ZEPHIR_EQUALS                         19
#define ZEPHIR_IDENTICAL                      20
#define ZEPHIR_LESS                           21
#define ZEPHIR_GREATER                        22
#define ZEPHIR_LESSEQUAL                      23
#define ZEPHIR_GREATEREQUAL                   24
#define ZEPHIR_NOTIDENTICAL                   25
#define ZEPHIR_NOTEQUALS                      26
#define ZEPHIR_ADD                            27
#define ZEPHIR_SUB                            28
#define ZEPHIR_CONCAT                         29
#define ZEPHIR_MUL                            30
#define ZEPHIR_DIV                            31
#define ZEPHIR_MOD                            32
#define ZEPHIR_ISSET                          33
#define ZEPHIR_FETCH                          34
#define ZEPHIR_EMPTY                          35
#define ZEPHIR_TYPEOF                         36
#define ZEPHIR_CLONE                          37
#define ZEPHIR_NEW                            38
#define ZEPHIR_NOT                            39
#define ZEPHIR_PARENTHESES_CLOSE              40
#define ZEPHIR_SBRACKET_OPEN                  41
#define ZEPHIR_ARROW                          42
#define ZEPHIR_NAMESPACE                      43
#define ZEPHIR_IDENTIFIER                     44
#define ZEPHIR_DOTCOMMA                       45
#define ZEPHIR_USE                            46
#define ZEPHIR_AS                             47
#define ZEPHIR_INTERFACE                      48
#define ZEPHIR_EXTENDS                        49
#define ZEPHIR_CLASS                          50
#define ZEPHIR_IMPLEMENTS                     51
#define ZEPHIR_ABSTRACT                       52
#define ZEPHIR_FINAL                          53
#define ZEPHIR_BRACKET_OPEN                   54
#define ZEPHIR_BRACKET_CLOSE                  55
#define ZEPHIR_COMMENT                        56
#define ZEPHIR_ASSIGN                         57
#define ZEPHIR_CONST                          58
#define ZEPHIR_CONSTANT                       59
#define ZEPHIR_FUNCTION                       60
#define ZEPHIR_PARENTHESES_OPEN               61
#define ZEPHIR_INLINE                         62
#define ZEPHIR_VOID                           63
#define ZEPHIR_NULL                           64
#define ZEPHIR_THIS                           65
#define ZEPHIR_SBRACKET_CLOSE                 66
#define ZEPHIR_TYPE_INTEGER                   67
#define ZEPHIR_TYPE_UINTEGER                  68
#define ZEPHIR_TYPE_LONG                      69
#define ZEPHIR_TYPE_ULONG                     70
#define ZEPHIR_TYPE_CHAR                      71
#define ZEPHIR_TYPE_UCHAR                     72
#define ZEPHIR_TYPE_DOUBLE                    73
#define ZEPHIR_TYPE_BOOL                      74
#define ZEPHIR_TYPE_STRING                    75
#define ZEPHIR_TYPE_ARRAY                     76
#define ZEPHIR_TYPE_VAR                       77
#define ZEPHIR_TYPE_CALLABLE                  78
#define ZEPHIR_TYPE_RESOURCE                  79
#define ZEPHIR_TYPE_OBJECT                    80
#define ZEPHIR_BREAK                          81
#define ZEPHIR_CONTINUE                       82
#define ZEPHIR_IF                             83
#define ZEPHIR_ELSE                           84
#define ZEPHIR_SWITCH                         85
#define ZEPHIR_CASE                           86
#define ZEPHIR_COLON                          87
#define ZEPHIR_DEFAULT                        88
#define ZEPHIR_LOOP                           89
#define ZEPHIR_WHILE                          90
#define ZEPHIR_DO                             91
#define ZEPHIR_TRY                            92
#define ZEPHIR_CATCH                          93
#define ZEPHIR_FOR                            94
#define ZEPHIR_IN                             95
#define ZEPHIR_REVERSE                        96
#define ZEPHIR_LET                            97
#define ZEPHIR_ADDASSIGN                      98
#define ZEPHIR_SUBASSIGN                      99
#define ZEPHIR_MULASSIGN                      100
#define ZEPHIR_DIVASSIGN                      101
#define ZEPHIR_CONCATASSIGN                   102
#define ZEPHIR_MODASSIGN                      103
#define ZEPHIR_STRING                         104
#define ZEPHIR_DOUBLECOLON                    105
#define ZEPHIR_INCR                           106
#define ZEPHIR_DECR                           107
#define ZEPHIR_ECHO                           108
#define ZEPHIR_RETURN                         109
#define ZEPHIR_UNSET                          110
#define ZEPHIR_THROW                          111
#define ZEPHIR_INTEGER                        112
#define ZEPHIR_CHAR                           113
#define ZEPHIR_DOUBLE                         114
#define ZEPHIR_TRUE                           115
#define ZEPHIR_FALSE                          116
#define ZEPHIR_CBLOCK                         117
