<?php
/**
 * @var string $fullName
 * @var string $className
 * @var array $methods
 * @var string[] $namespacePieces
 * @var \Zephir\Class\ClassDefinition $classDefinition
 * @var Zephir\CompilerFile $compilerFile
 */

$items = [
    ['name' => 'Classes' , 'url' => '/classes.html'],
    $items[] = ['name' => $fullName]
];
?>

<?= $this->partial('partials/breadcrumb.phtml', ['items'=> $items]) ?>

<div class="class-header clearfix">

    <div class="access-buttons">
        <a class="zep-button" href="<?= $this->url(Zephir\Documentation::sourceUrl($classDefinition)) ?>">Source</a>
        <?php if ($this->themeOption('github')) { ?>
        <a class="zep-button"
           href="<?= rtrim($this->themeOption('github'), '/') . "/tree/master/{$compilerFile->getFilePath()}" ?>">
            GitHub
        </a>
        <?php } ?>
    </div>

    <div class="class-full-name">
        <span class="class-type">Class</span>

        <?php foreach ($namespacePieces as $nsname => $nspath) { ?>
        <span class="namespace-piece">
            <a href="<?= $this->url(Zephir\Documentation::namespaceUrl($nspath)) ?>">
                <?=$nsname?>
            </a>
        </span>
        <?php } ?>

        <h1 class="class-name"><?= $className ?></h1>
    </div>
</div>


<div class="hidden-anchor"  id="methods"></div>
<div class="methods-summary standard-bandeau">Methods</div>

<ul class="method-summary-list">
    <?php foreach ($methods as $method): ?>
        <?= $this->partial('partials/class/method-summary.phtml', ['method' => $method]) ?>
    <?php endforeach; ?>
</ul>

<div class="hidden-anchor" id="methods-details"></div>
<div class="methods-summary standard-bandeau">Methods Details</div>

<ul class="method-details-list">
    <?php foreach ($methods as $method): ?>
        <?= $this->partial('partials/class/method-details.phtml', ['method' => $method]) ?>
    <?php endforeach; ?>
</ul>
