<?php
/* @var $method \Zephir\ClassMethod */

$visibilities = $method->getVisibility();
$docblock =  $method->getParsedDocBlock();
?>

<li class="class-method clearfix">
    <div class="hidden-anchor" id="method-details-<?= $method->getName() ?>"></div>
    <div class="method-details">
        <div class="method-details-details">
            <div class="method-signature">
                <?php foreach($visibilities as $visibility): ?>
                    <span class="visibility-<?= $visibility ?> keyword"><?= $visibility ?></span>
                <?php endforeach; ?>
                <span class="keyword">function</span>&nbsp;<span class="method-name"><?= $method->getName() ?></span>(<?= $this->partial("partials/class/method-summary-params.phtml" ) ?>)
            </div>
            <div class="method-doc">
                <?php if ($docblock):  ?>
                    <div class="summary">
                        <?= $docblock->getSummary() ?>
                    </div>
                    <div class="description">
                        <?= $docblock->getDescription() ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</li>
