<?php
/**
 * @var $method \Zephir\Class\ClassMethod
 */

if ($method->getParameters()) {
    $i = 0;
    $parameters = [];

    foreach ($method->getParameters() as $param) {
        if ($param['data-type']) {
            $parameters[$i] = '<span class="param-data-type">'.$param['data-type'].'</span> ';
        }
        $parameters[$i] .= '<span class="variable param-name">$'.$param['name'].'</span>';

        $i++;
    }

    echo trim(implode(', ', $parameters));
}
