
extern zend_class_entry *stub_oo_constantsinterface_ce;

ZEPHIR_INIT_CLASS(Stub_Oo_ConstantsInterface);

PHP_METHOD(Stub_Oo_ConstantsInterface, testReadInterfaceConstant1);
PHP_METHOD(Stub_Oo_ConstantsInterface, testReadInterfaceConstant2);
PHP_METHOD(Stub_Oo_ConstantsInterface, testReadInterfaceConstant3);
PHP_METHOD(Stub_Oo_ConstantsInterface, testReadInterfaceConstant4);
PHP_METHOD(Stub_Oo_ConstantsInterface, testReadInterfaceConstant5);
PHP_METHOD(Stub_Oo_ConstantsInterface, testReadInterfaceConstant6);

ZEND_BEGIN_ARG_INFO_EX(arginfo_stub_oo_constantsinterface_testreadinterfaceconstant1, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_stub_oo_constantsinterface_testreadinterfaceconstant2, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_stub_oo_constantsinterface_testreadinterfaceconstant3, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_stub_oo_constantsinterface_testreadinterfaceconstant4, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_stub_oo_constantsinterface_testreadinterfaceconstant5, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_stub_oo_constantsinterface_testreadinterfaceconstant6, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(stub_oo_constantsinterface_method_entry) {
	PHP_ME(Stub_Oo_ConstantsInterface, testReadInterfaceConstant1, arginfo_stub_oo_constantsinterface_testreadinterfaceconstant1, ZEND_ACC_PUBLIC)
	PHP_ME(Stub_Oo_ConstantsInterface, testReadInterfaceConstant2, arginfo_stub_oo_constantsinterface_testreadinterfaceconstant2, ZEND_ACC_PUBLIC)
	PHP_ME(Stub_Oo_ConstantsInterface, testReadInterfaceConstant3, arginfo_stub_oo_constantsinterface_testreadinterfaceconstant3, ZEND_ACC_PUBLIC)
	PHP_ME(Stub_Oo_ConstantsInterface, testReadInterfaceConstant4, arginfo_stub_oo_constantsinterface_testreadinterfaceconstant4, ZEND_ACC_PUBLIC)
	PHP_ME(Stub_Oo_ConstantsInterface, testReadInterfaceConstant5, arginfo_stub_oo_constantsinterface_testreadinterfaceconstant5, ZEND_ACC_PUBLIC)
	PHP_ME(Stub_Oo_ConstantsInterface, testReadInterfaceConstant6, arginfo_stub_oo_constantsinterface_testreadinterfaceconstant6, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
