<?php

/* @var $method \Zephir\ClassMethod */

?>

<li class="class-method clearfix">

    <div class="method-return">

        <?php
            $allTypes = [];
            $classes = [];

            foreach ($method->getReturnTypes()->getObjectLikeReturnTypes() as $type) {
                $allTypes[] = $type->getValue();
            }

            foreach ($method->getReturnTypes()->getRealReturnTypes() as $type) {
                $allTypes[] = $type->getDataType();
            }

            echo implode(' | ', \array_unique($allTypes, \SORT_STRING));
        ?>

    </div>
    <div class="method-summary">
        <span class="method-name"><a href="#method-details-<?= $method->getName() ?>"><?= $method->getName() ?></a></span>(<?= $this->partial("partials/class/method-summary-params.phtml" ) ?>)

    </div>

</li>
