#define XX_PUBLIC                          1
#define XX_PROTECTED                       2
#define XX_STATIC                          3
#define XX_PRIVATE                         4
#define XX_SCOPED                          5
#define XX_COMMA                           6
#define XX_REQUIRE                         7
#define XX_QUESTION                        8
#define XX_LIKELY                          9
#define XX_UNLIKELY                       10
#define XX_INSTANCEOF                     11
#define XX_NOT                            12
#define XX_OR                             13
#define XX_AND                            14
#define XX_BITWISE_OR                     15
#define XX_BITWISE_AND                    16
#define XX_BITWISE_XOR                    17
#define XX_BITWISE_SHIFTLEFT              18
#define XX_BITWISE_SHIFTRIGHT             19
#define XX_EQUALS                         20
#define XX_IDENTICAL                      21
#define XX_LESS                           22
#define XX_GREATER                        23
#define XX_LESSEQUAL                      24
#define XX_GREATEREQUAL                   25
#define XX_NOTIDENTICAL                   26
#define XX_NOTEQUALS                      27
#define XX_ADD                            28
#define XX_SUB                            29
#define XX_CONCAT                         30
#define XX_MUL                            31
#define XX_DIV                            32
#define XX_MOD                            33
#define XX_CLONE                          34
#define XX_EMPTY                          35
#define XX_ISSET                          36
#define XX_FETCH                          37
#define XX_TYPEOF                         38
#define XX_NEW                            39
#define XX_PARENTHESES_CLOSE              40
#define XX_SBRACKET_OPEN                  41
#define XX_ARROW                          42
#define XX_NAMESPACE                      43
#define XX_IDENTIFIER                     44
#define XX_DOTCOMMA                       45
#define XX_INTERFACE                      46
#define XX_EXTENDS                        47
#define XX_CLASS                          48
#define XX_IMPLEMENTS                     49
#define XX_ABSTRACT                       50
#define XX_FINAL                          51
#define XX_BRACKET_OPEN                   52
#define XX_BRACKET_CLOSE                  53
#define XX_COMMENT                        54
#define XX_ASSIGN                         55
#define XX_CONST                          56
#define XX_CONSTANT                       57
#define XX_FUNCTION                       58
#define XX_PARENTHESES_OPEN               59
#define XX_INLINE                         60
#define XX_VOID                           61
#define XX_SBRACKET_CLOSE                 62
#define XX_TYPE_INTEGER                   63
#define XX_TYPE_UINTEGER                  64
#define XX_TYPE_LONG                      65
#define XX_TYPE_ULONG                     66
#define XX_TYPE_CHAR                      67
#define XX_TYPE_UCHAR                     68
#define XX_TYPE_DOUBLE                    69
#define XX_TYPE_BOOL                      70
#define XX_TYPE_STRING                    71
#define XX_TYPE_ARRAY                     72
#define XX_TYPE_VAR                       73
#define XX_BREAK                          74
#define XX_CONTINUE                       75
#define XX_IF                             76
#define XX_ELSE                           77
#define XX_SWITCH                         78
#define XX_CASE                           79
#define XX_COLON                          80
#define XX_DEFAULT                        81
#define XX_LOOP                           82
#define XX_WHILE                          83
#define XX_DO                             84
#define XX_FOR                            85
#define XX_IN                             86
#define XX_REVERSE                        87
#define XX_LET                            88
#define XX_ADDASSIGN                      89
#define XX_SUBASSIGN                      90
#define XX_MULASSIGN                      91
#define XX_DIVASSIGN                      92
#define XX_CONCATASSIGN                   93
#define XX_MODASSIGN                      94
#define XX_STRING                         95
#define XX_DOUBLECOLON                    96
#define XX_INCR                           97
#define XX_DECR                           98
#define XX_ECHO                           99
#define XX_RETURN                         100
#define XX_UNSET                          101
#define XX_THROW                          102
#define XX_INTEGER                        103
#define XX_CHAR                           104
#define XX_DOUBLE                         105
#define XX_NULL                           106
#define XX_TRUE                           107
#define XX_FALSE                          108
#define XX_CBLOCK                         109
