#define XX_PUBLIC                          1
#define XX_PROTECTED                       2
#define XX_STATIC                          3
#define XX_PRIVATE                         4
#define XX_SCOPED                          5
#define XX_COMMA                           6
#define XX_AND                             7
#define XX_OR                              8
#define XX_EQUALS                          9
#define XX_IDENTICAL                      10
#define XX_LESS                           11
#define XX_GREATER                        12
#define XX_LESSEQUAL                      13
#define XX_GREATEREQUAL                   14
#define XX_NOTIDENTICAL                   15
#define XX_NOTEQUALS                      16
#define XX_ADD                            17
#define XX_SUB                            18
#define XX_CONCAT                         19
#define XX_MUL                            20
#define XX_DIV                            21
#define XX_ISSET                          22
#define XX_FETCH                          23
#define XX_TYPEOF                         24
#define XX_INSTANCEOF                     25
#define XX_NEW                            26
#define XX_NOT                            27
#define XX_PARENTHESES_CLOSE              28
#define XX_NAMESPACE                      29
#define XX_IDENTIFIER                     30
#define XX_DOTCOMMA                       31
#define XX_CLASS                          32
#define XX_BRACKET_OPEN                   33
#define XX_BRACKET_CLOSE                  34
#define XX_EXTENDS                        35
#define XX_ABSTRACT                       36
#define XX_COMMENT                        37
#define XX_ASSIGN                         38
#define XX_CONST                          39
#define XX_CONSTANT                       40
#define XX_FUNCTION                       41
#define XX_PARENTHESES_OPEN               42
#define XX_INLINE                         43
#define XX_FINAL                          44
#define XX_TYPE_INTEGER                   45
#define XX_TYPE_UINTEGER                  46
#define XX_TYPE_LONG                      47
#define XX_TYPE_ULONG                     48
#define XX_TYPE_CHAR                      49
#define XX_TYPE_UCHAR                     50
#define XX_TYPE_DOUBLE                    51
#define XX_TYPE_BOOL                      52
#define XX_TYPE_STRING                    53
#define XX_TYPE_ARRAY                     54
#define XX_TYPE_VAR                       55
#define XX_BREAK                          56
#define XX_CONTINUE                       57
#define XX_IF                             58
#define XX_ELSE                           59
#define XX_SWITCH                         60
#define XX_CASE                           61
#define XX_COLON                          62
#define XX_DEFAULT                        63
#define XX_LOOP                           64
#define XX_WHILE                          65
#define XX_DO                             66
#define XX_FOR                            67
#define XX_IN                             68
#define XX_REVERSE                        69
#define XX_LET                            70
#define XX_ADDASSIGN                      71
#define XX_SUBASSIGN                      72
#define XX_MULASSIGN                      73
#define XX_DIVASSIGN                      74
#define XX_CONCATASSIGN                   75
#define XX_ARROW                          76
#define XX_SBRACKET_OPEN                  77
#define XX_SBRACKET_CLOSE                 78
#define XX_DOUBLECOLON                    79
#define XX_INCR                           80
#define XX_DECR                           81
#define XX_ECHO                           82
#define XX_RETURN                         83
#define XX_UNSET                          84
#define XX_INTEGER                        85
#define XX_STRING                         86
#define XX_THROW                          87
#define XX_SCHAR                          88
#define XX_DOUBLE                         89
#define XX_NULL                           90
#define XX_TRUE                           91
#define XX_FALSE                          92
