#define XX_PUBLIC                          1
#define XX_PROTECTED                       2
#define XX_STATIC                          3
#define XX_PRIVATE                         4
#define XX_SCOPED                          5
#define XX_COMMA                           6
#define XX_REQUIRE                         7
#define XX_QUESTION                        8
#define XX_LIKELY                          9
#define XX_UNLIKELY                       10
#define XX_ISSET                          11
#define XX_FETCH                          12
#define XX_EMPTY                          13
#define XX_TYPEOF                         14
#define XX_INSTANCEOF                     15
#define XX_OR                             16
#define XX_AND                            17
#define XX_BITWISE_OR                     18
#define XX_BITWISE_AND                    19
#define XX_BITWISE_XOR                    20
#define XX_BITWISE_SHIFTLEFT              21
#define XX_BITWISE_SHIFTRIGHT             22
#define XX_EQUALS                         23
#define XX_IDENTICAL                      24
#define XX_LESS                           25
#define XX_GREATER                        26
#define XX_LESSEQUAL                      27
#define XX_GREATEREQUAL                   28
#define XX_NOTIDENTICAL                   29
#define XX_NOTEQUALS                      30
#define XX_ADD                            31
#define XX_SUB                            32
#define XX_CONCAT                         33
#define XX_MUL                            34
#define XX_DIV                            35
#define XX_MOD                            36
#define XX_CLONE                          37
#define XX_NEW                            38
#define XX_NOT                            39
#define XX_PARENTHESES_CLOSE              40
#define XX_SBRACKET_OPEN                  41
#define XX_ARROW                          42
#define XX_NAMESPACE                      43
#define XX_IDENTIFIER                     44
#define XX_DOTCOMMA                       45
#define XX_USE                            46
#define XX_AS                             47
#define XX_INTERFACE                      48
#define XX_EXTENDS                        49
#define XX_CLASS                          50
#define XX_IMPLEMENTS                     51
#define XX_ABSTRACT                       52
#define XX_FINAL                          53
#define XX_BRACKET_OPEN                   54
#define XX_BRACKET_CLOSE                  55
#define XX_COMMENT                        56
#define XX_ASSIGN                         57
#define XX_CONST                          58
#define XX_CONSTANT                       59
#define XX_FUNCTION                       60
#define XX_PARENTHESES_OPEN               61
#define XX_INLINE                         62
#define XX_VOID                           63
#define XX_SBRACKET_CLOSE                 64
#define XX_TYPE_INTEGER                   65
#define XX_TYPE_UINTEGER                  66
#define XX_TYPE_LONG                      67
#define XX_TYPE_ULONG                     68
#define XX_TYPE_CHAR                      69
#define XX_TYPE_UCHAR                     70
#define XX_TYPE_DOUBLE                    71
#define XX_TYPE_BOOL                      72
#define XX_TYPE_STRING                    73
#define XX_TYPE_ARRAY                     74
#define XX_TYPE_VAR                       75
#define XX_BREAK                          76
#define XX_CONTINUE                       77
#define XX_IF                             78
#define XX_ELSE                           79
#define XX_SWITCH                         80
#define XX_CASE                           81
#define XX_COLON                          82
#define XX_DEFAULT                        83
#define XX_LOOP                           84
#define XX_WHILE                          85
#define XX_DO                             86
#define XX_FOR                            87
#define XX_IN                             88
#define XX_REVERSE                        89
#define XX_LET                            90
#define XX_ADDASSIGN                      91
#define XX_SUBASSIGN                      92
#define XX_MULASSIGN                      93
#define XX_DIVASSIGN                      94
#define XX_CONCATASSIGN                   95
#define XX_MODASSIGN                      96
#define XX_STRING                         97
#define XX_DOUBLECOLON                    98
#define XX_INCR                           99
#define XX_DECR                           100
#define XX_ECHO                           101
#define XX_RETURN                         102
#define XX_UNSET                          103
#define XX_THROW                          104
#define XX_INTEGER                        105
#define XX_CHAR                           106
#define XX_DOUBLE                         107
#define XX_NULL                           108
#define XX_TRUE                           109
#define XX_FALSE                          110
#define XX_CBLOCK                         111
