/* Generated by re2c 0.13.5 on Fri Aug 23 10:11:13 2013 */
// 1 "scanner.re"

/*
 +----------------------------------------------------------------------+
 | Zephir Language                                                      |
 +----------------------------------------------------------------------+
 | Copyright (c) 2013 Zephir Team                                       |
 +----------------------------------------------------------------------+
 | This source file is subject to version 1.0 of the Zephir license,    |
 | that is bundled with this package in the file LICENSE, and is        |
 | available through the world-wide-web at the following url:           |
 | http://www.zephir-lang.com/license                                   |
 |                                                                      |
 | If you did not receive a copy of the Zephir license and are unable   |
 | to obtain it through the world-wide-web, please send a note to       |
 | license@zephir-lang.com so we can mail you a copy immediately.       |
 +----------------------------------------------------------------------+
*/

#include "string.h"
#include "scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int xx_get_token(xx_scanner_state *s, xx_scanner_token *token) {

	char next, *q = YYCURSOR, *start = YYCURSOR;
	int status = XX_SCANNER_RETCODE_IMPOSSIBLE;

	while (XX_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
// 38 "scanner.c"
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy68;
			case '\t':
			case '\r':
			case ' ':	goto yy64;
			case '\n':	goto yy66;
			case '!':	goto yy43;
			case '"':	goto yy25;
			case '&':	goto yy45;
			case '\'':	goto yy23;
			case '(':	goto yy29;
			case ')':	goto yy31;
			case '*':	goto yy51;
			case '+':	goto yy49;
			case ',':	goto yy62;
			case '-':	goto yy2;
			case '.':	goto yy52;
			case '/':	goto yy26;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy4;
			case ':':	goto yy58;
			case ';':	goto yy60;
			case '<':	goto yy54;
			case '=':	goto yy47;
			case '>':	goto yy56;
			case '@':	goto yy41;
			case 'A':
			case 'a':	goto yy10;
			case 'B':
			case 'b':	goto yy19;
			case 'C':
			case 'c':	goto yy11;
			case 'D':
			case 'd':	goto yy18;
			case 'E':
			case 'e':	goto yy12;
			case 'F':
			case 'f':	goto yy8;
			case 'G':
			case 'H':
			case 'J':
			case 'K':
			case 'M':
			case 'O':
			case 'Q':
			case 'X':
			case 'Y':
			case 'Z':
			case 'g':
			case 'h':
			case 'j':
			case 'k':
			case 'm':
			case 'o':
			case 'q':
			case 'x':
			case 'y':
			case 'z':	goto yy28;
			case 'I':
			case 'i':	goto yy15;
			case 'L':
			case 'l':	goto yy16;
			case 'N':
			case 'n':	goto yy6;
			case 'P':
			case 'p':	goto yy13;
			case 'R':
			case 'r':	goto yy22;
			case 'S':
			case 's':	goto yy14;
			case 'T':
			case 't':	goto yy9;
			case 'U':
			case 'u':	goto yy17;
			case 'V':
			case 'v':	goto yy20;
			case 'W':
			case 'w':	goto yy21;
			case '[':	goto yy37;
			case '\\':
			case '_':	goto yy27;
			case ']':	goto yy39;
			case '{':	goto yy33;
			case '|':	goto yy46;
			case '}':	goto yy35;
			default:	goto yy70;
			}
yy2:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '-':	goto yy370;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy365;
			case '=':	goto yy374;
			case '>':	goto yy372;
			default:	goto yy3;
			}
yy3:
// 565 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SUB;
			return 0;
		}
// 164 "scanner.c"
yy4:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			goto yy366;
yy5:
// 39 "scanner.re"
			{
			token->opcode = XX_T_INTEGER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 179 "scanner.c"
yy6:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case 'A':
			case 'a':	goto yy348;
			case 'E':
			case 'e':	goto yy349;
			case 'U':
			case 'u':	goto yy350;
			default:	goto yy98;
			}
yy7:
// 394 "scanner.re"
			{
			token->opcode = XX_T_IDENTIFIER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 201 "scanner.c"
yy8:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy320;
			case 'E':
			case 'e':	goto yy321;
			case 'L':
			case 'l':	goto yy322;
			case 'N':
			case 'n':	goto yy323;
			case 'O':
			case 'o':	goto yy325;
			case 'U':
			case 'u':	goto yy326;
			default:	goto yy98;
			}
yy9:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy305;
			case 'R':
			case 'r':	goto yy306;
			case 'Y':
			case 'y':	goto yy307;
			default:	goto yy98;
			}
yy10:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy297;
			default:	goto yy98;
			}
yy11:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy273;
			case 'H':
			case 'h':	goto yy274;
			case 'L':
			case 'l':	goto yy275;
			case 'O':
			case 'o':	goto yy276;
			default:	goto yy98;
			}
yy12:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy258;
			case 'L':
			case 'l':	goto yy259;
			case 'X':
			case 'x':	goto yy260;
			default:	goto yy98;
			}
yy13:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy237;
			case 'U':
			case 'u':	goto yy238;
			default:	goto yy98;
			}
yy14:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy220;
			case 'W':
			case 'w':	goto yy221;
			default:	goto yy98;
			}
yy15:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy195;
			case 'N':
			case 'n':	goto yy197;
			case 'S':
			case 's':	goto yy199;
			default:	goto yy98;
			}
yy16:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy185;
			case 'O':
			case 'o':	goto yy186;
			default:	goto yy98;
			}
yy17:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy166;
			case 'I':
			case 'i':	goto yy167;
			case 'L':
			case 'l':	goto yy168;
			case 'N':
			case 'n':	goto yy169;
			default:	goto yy98;
			}
yy18:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy153;
			case 'O':
			case 'o':	goto yy154;
			default:	goto yy98;
			}
yy19:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy140;
			case 'R':
			case 'r':	goto yy141;
			default:	goto yy98;
			}
yy20:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy137;
			default:	goto yy98;
			}
yy21:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy132;
			default:	goto yy98;
			}
yy22:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy120;
			default:	goto yy98;
			}
yy23:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych >= 0x01) goto yy116;
yy24:
// 619 "scanner.re"
			{
			status = XX_SCANNER_RETCODE_ERR;
			break;
		}
// 361 "scanner.c"
yy25:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy24;
			goto yy110;
yy26:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case '*':	goto yy104;
			case '/':	goto yy101;
			case '=':	goto yy99;
			default:	goto yy24;
			}
yy27:
			yych = *++YYCURSOR;
			goto yy98;
yy28:
			yych = *++YYCURSOR;
			goto yy98;
yy29:
			++YYCURSOR;
// 403 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_PARENTHESES_OPEN;
			return 0;
		}
// 390 "scanner.c"
yy31:
			++YYCURSOR;
// 409 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_PARENTHESES_CLOSE;
			return 0;
		}
// 399 "scanner.c"
yy33:
			++YYCURSOR;
// 415 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_BRACKET_OPEN;
			return 0;
		}
// 408 "scanner.c"
yy35:
			++YYCURSOR;
// 421 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_BRACKET_CLOSE;
			return 0;
		}
// 417 "scanner.c"
yy37:
			++YYCURSOR;
// 427 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SBRACKET_OPEN;
			return 0;
		}
// 426 "scanner.c"
yy39:
			++YYCURSOR;
// 433 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SBRACKET_CLOSE;
			return 0;
		}
// 435 "scanner.c"
yy41:
			++YYCURSOR;
// 439 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_AT;
			return 0;
		}
// 444 "scanner.c"
yy43:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy93;
			default:	goto yy44;
			}
yy44:
// 445 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_NOT;
			return 0;
		}
// 458 "scanner.c"
yy45:
			yych = *++YYCURSOR;
			switch (yych) {
			case '&':	goto yy91;
			default:	goto yy24;
			}
yy46:
			yych = *++YYCURSOR;
			switch (yych) {
			case '|':	goto yy89;
			default:	goto yy24;
			}
yy47:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy85;
			default:	goto yy48;
			}
yy48:
// 463 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_ASSIGN;
			return 0;
		}
// 484 "scanner.c"
yy49:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '+':	goto yy81;
			case '=':	goto yy83;
			default:	goto yy50;
			}
yy50:
// 559 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_ADD;
			return 0;
		}
// 499 "scanner.c"
yy51:
			yych = *++YYCURSOR;
			switch (yych) {
			case '=':	goto yy79;
			default:	goto yy24;
			}
yy52:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy77;
			default:	goto yy53;
			}
yy53:
// 553 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_DOT;
			return 0;
		}
// 519 "scanner.c"
yy54:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy75;
			default:	goto yy55;
			}
yy55:
// 535 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_LESS;
			return 0;
		}
// 533 "scanner.c"
yy56:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy73;
			default:	goto yy57;
			}
yy57:
// 541 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_GREATER;
			return 0;
		}
// 547 "scanner.c"
yy58:
			++YYCURSOR;
// 583 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_COLON;
			return 0;
		}
// 556 "scanner.c"
yy60:
			++YYCURSOR;
// 589 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_DOTCOMMA;
			return 0;
		}
// 565 "scanner.c"
yy62:
			++YYCURSOR;
// 595 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_COMMA;
			return 0;
		}
// 574 "scanner.c"
yy64:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy72;
yy65:
// 601 "scanner.re"
			{
			s->active_char += (YYCURSOR - start);
			token->opcode = XX_T_IGNORE;
			return 0;
		}
// 586 "scanner.c"
yy66:
			++YYCURSOR;
// 607 "scanner.re"
			{
			s->active_line++;
			s->active_char = 0;
			token->opcode = XX_T_IGNORE;
			return 0;
		}
// 596 "scanner.c"
yy68:
			++YYCURSOR;
// 614 "scanner.re"
			{
			status = XX_SCANNER_RETCODE_EOF;
			break;
		}
// 604 "scanner.c"
yy70:
			yych = *++YYCURSOR;
			goto yy24;
yy71:
			++YYCURSOR;
			yych = *YYCURSOR;
yy72:
			switch (yych) {
			case '\t':
			case '\r':
			case ' ':	goto yy71;
			default:	goto yy65;
			}
yy73:
			++YYCURSOR;
// 529 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_GREATEREQUAL;
			return 0;
		}
// 626 "scanner.c"
yy75:
			++YYCURSOR;
// 523 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_LESSEQUAL;
			return 0;
		}
// 635 "scanner.c"
yy77:
			++YYCURSOR;
// 493 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_CONCATASSIGN;
			return 0;
		}
// 644 "scanner.c"
yy79:
			++YYCURSOR;
// 481 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_MULASSIGN;
			return 0;
		}
// 653 "scanner.c"
yy81:
			++YYCURSOR;
// 571 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_INCR;
			return 0;
		}
// 662 "scanner.c"
yy83:
			++YYCURSOR;
// 469 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_ADDASSIGN;
			return 0;
		}
// 671 "scanner.c"
yy85:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy87;
			default:	goto yy86;
			}
yy86:
// 499 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_EQUALS;
			return 0;
		}
// 685 "scanner.c"
yy87:
			++YYCURSOR;
// 511 "scanner.re"
			{
			s->active_char += 3;
			token->opcode = XX_T_IDENTICAL;
			return 0;
		}
// 694 "scanner.c"
yy89:
			++YYCURSOR;
// 457 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_OR;
			return 0;
		}
// 703 "scanner.c"
yy91:
			++YYCURSOR;
// 451 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_AND;
			return 0;
		}
// 712 "scanner.c"
yy93:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy95;
			default:	goto yy94;
			}
yy94:
// 505 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_NOTEQUALS;
			return 0;
		}
// 726 "scanner.c"
yy95:
			++YYCURSOR;
// 517 "scanner.re"
			{
			s->active_char += 3;
			token->opcode = XX_T_NOTIDENTICAL;
			return 0;
		}
// 735 "scanner.c"
yy97:
			++YYCURSOR;
			yych = *YYCURSOR;
yy98:
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy7;
			}
yy99:
			++YYCURSOR;
// 487 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_DIVASSIGN;
			return 0;
		}
// 815 "scanner.c"
yy101:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':
			case '\r':	goto yy103;
			default:	goto yy101;
			}
yy103:
// 373 "scanner.re"
			{
			token->opcode = XX_T_COMMENT;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			{
				int k, ch = s->active_char;
				for (k = 0; k < (token->len - 1); k++) {
					if (token->value[k] == '\n') {
						ch = 1;
						s->active_line++;
					} else {
						ch++;
					}
				}
				s->active_char = ch;
			}
			q = YYCURSOR;
			return 0;
		}
// 845 "scanner.c"
yy104:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':	goto yy106;
			default:	goto yy104;
			}
yy106:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':	goto yy106;
			case '/':	goto yy108;
			default:	goto yy104;
			}
yy108:
			yych = *++YYCURSOR;
			goto yy103;
yy109:
			++YYCURSOR;
			yych = *YYCURSOR;
yy110:
			switch (yych) {
			case 0x00:	goto yy111;
			case '"':	goto yy113;
			case '\\':	goto yy112;
			default:	goto yy109;
			}
yy111:
			YYCURSOR = YYMARKER;
			switch (yyaccept) {
			case 0: 	goto yy5;
			case 1: 	goto yy24;
			}
yy112:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy111;
			default:	goto yy109;
			}
yy113:
			++YYCURSOR;
// 363 "scanner.re"
			{
			token->opcode = XX_T_STRING;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 898 "scanner.c"
yy115:
			++YYCURSOR;
			yych = *YYCURSOR;
yy116:
			switch (yych) {
			case 0x00:	goto yy111;
			case '\'':	goto yy118;
			case '\\':	goto yy117;
			default:	goto yy115;
			}
yy117:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy111;
			default:	goto yy115;
			}
yy118:
			++YYCURSOR;
// 353 "scanner.re"
			{
			token->opcode = XX_T_SCHAR;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 927 "scanner.c"
yy120:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy121;
			case 'V':
			case 'v':	goto yy122;
			default:	goto yy98;
			}
yy121:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy128;
			default:	goto yy98;
			}
yy122:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy123;
			default:	goto yy98;
			}
yy123:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy124;
			default:	goto yy98;
			}
yy124:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy125;
			default:	goto yy98;
			}
yy125:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy126;
			default:	goto yy98;
			}
yy126:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy127;
			}
yy127:
// 346 "scanner.re"
			{
			token->opcode = XX_T_REVERSE;
			s->active_char += sizeof("reverse")-1;
			return 0;
		}
// 1048 "scanner.c"
yy128:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy129;
			default:	goto yy98;
			}
yy129:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy130;
			default:	goto yy98;
			}
yy130:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy131;
			}
yy131:
// 268 "scanner.re"
			{
			s->active_char += sizeof("return")-1;
			token->opcode = XX_T_RETURN;
			return 0;
		}
// 1139 "scanner.c"
yy132:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy133;
			default:	goto yy98;
			}
yy133:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy134;
			default:	goto yy98;
			}
yy134:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy135;
			default:	goto yy98;
			}
yy135:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy136;
			}
yy136:
// 244 "scanner.re"
			{
			s->active_char += sizeof("while")-1;
			token->opcode = XX_T_WHILE;
			return 0;
		}
// 1237 "scanner.c"
yy137:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy138;
			default:	goto yy98;
			}
yy138:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy139;
			}
yy139:
// 226 "scanner.re"
			{
			s->active_char += sizeof("var")-1;
			token->opcode = XX_T_TYPE_VAR;
			return 0;
		}
// 1321 "scanner.c"
yy140:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy146;
			default:	goto yy98;
			}
yy141:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy142;
			default:	goto yy98;
			}
yy142:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy143;
			default:	goto yy98;
			}
yy143:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'K':
			case 'k':	goto yy144;
			default:	goto yy98;
			}
yy144:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy145;
			}
yy145:
// 280 "scanner.re"
			{
			token->opcode = XX_T_BREAK;
			s->active_char += sizeof("break")-1;
			return 0;
		}
// 1426 "scanner.c"
yy146:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy147;
			default:	goto yy98;
			}
yy147:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			case 'E':
			case 'e':	goto yy149;
			default:	goto yy148;
			}
yy148:
// 208 "scanner.re"
			{
			s->active_char += sizeof("bool")-1;
			token->opcode = XX_T_TYPE_BOOL;
			return 0;
		}
// 1510 "scanner.c"
yy149:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy150;
			default:	goto yy98;
			}
yy150:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy151;
			default:	goto yy98;
			}
yy151:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy152;
			}
yy152:
// 214 "scanner.re"
			{
			s->active_char += sizeof("boolean")-1;
			token->opcode = XX_T_TYPE_BOOL;
			return 0;
		}
// 1601 "scanner.c"
yy153:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy160;
			default:	goto yy98;
			}
yy154:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy155;
			default:	goto yy98;
			}
yy155:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy156;
			default:	goto yy98;
			}
yy156:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy157;
			default:	goto yy98;
			}
yy157:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy158;
			default:	goto yy98;
			}
yy158:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy159;
			}
yy159:
// 196 "scanner.re"
			{
			s->active_char += sizeof("double")-1;
			token->opcode = XX_T_TYPE_DOUBLE;
			return 0;
		}
// 1713 "scanner.c"
yy160:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy161;
			default:	goto yy98;
			}
yy161:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy162;
			default:	goto yy98;
			}
yy162:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy163;
			default:	goto yy98;
			}
yy163:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy164;
			default:	goto yy98;
			}
yy164:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy165;
			}
yy165:
// 340 "scanner.re"
			{
			token->opcode = XX_T_DEFAULT;
			s->active_char += sizeof("default")-1;
			return 0;
		}
// 1818 "scanner.c"
yy166:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy181;
			default:	goto yy98;
			}
yy167:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy178;
			default:	goto yy98;
			}
yy168:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy174;
			default:	goto yy98;
			}
yy169:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy170;
			default:	goto yy98;
			}
yy170:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy171;
			default:	goto yy98;
			}
yy171:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy172;
			default:	goto yy98;
			}
yy172:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy173;
			}
yy173:
// 310 "scanner.re"
			{
			token->opcode = XX_T_UNSET;
			s->active_char += sizeof("unset")-1;
			return 0;
		}
// 1937 "scanner.c"
yy174:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy175;
			default:	goto yy98;
			}
yy175:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy176;
			default:	goto yy98;
			}
yy176:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy177;
			}
yy177:
// 178 "scanner.re"
			{
			s->active_char += sizeof("ulong")-1;
			token->opcode = XX_T_TYPE_ULONG;
			return 0;
		}
// 2028 "scanner.c"
yy178:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy179;
			default:	goto yy98;
			}
yy179:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy180;
			}
yy180:
// 166 "scanner.re"
			{
			s->active_char += sizeof("uint")-1;
			token->opcode = XX_T_TYPE_UINTEGER;
			return 0;
		}
// 2112 "scanner.c"
yy181:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy182;
			default:	goto yy98;
			}
yy182:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy183;
			default:	goto yy98;
			}
yy183:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy184;
			}
yy184:
// 190 "scanner.re"
			{
			s->active_char += sizeof("uchar")-1;
			token->opcode = XX_T_TYPE_UCHAR;
			return 0;
		}
// 2203 "scanner.c"
yy185:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy193;
			default:	goto yy98;
			}
yy186:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy187;
			case 'O':
			case 'o':	goto yy188;
			default:	goto yy98;
			}
yy187:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy191;
			default:	goto yy98;
			}
yy188:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy189;
			default:	goto yy98;
			}
yy189:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy190;
			}
yy190:
// 274 "scanner.re"
			{
			token->opcode = XX_T_LOOP;
			s->active_char += sizeof("loop")-1;
			return 0;
		}
// 2310 "scanner.c"
yy191:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy192;
			}
yy192:
// 172 "scanner.re"
			{
			s->active_char += sizeof("long")-1;
			token->opcode = XX_T_TYPE_LONG;
			return 0;
		}
// 2387 "scanner.c"
yy193:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy194;
			}
yy194:
// 142 "scanner.re"
			{
			s->active_char += sizeof("let")-1;
			token->opcode = XX_T_LET;
			return 0;
		}
// 2464 "scanner.c"
yy195:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy196;
			}
yy196:
// 232 "scanner.re"
			{
			s->active_char += sizeof("if")-1;
			token->opcode = XX_T_IF;
			return 0;
		}
// 2541 "scanner.c"
yy197:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			case 'L':
			case 'l':	goto yy204;
			case 'S':
			case 's':	goto yy207;
			case 'T':
			case 't':	goto yy205;
			default:	goto yy198;
			}
yy198:
// 256 "scanner.re"
			{
			s->active_char += sizeof("in")-1;
			token->opcode = XX_T_IN;
			return 0;
		}
// 2618 "scanner.c"
yy199:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy200;
			default:	goto yy98;
			}
yy200:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy201;
			default:	goto yy98;
			}
yy201:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy202;
			default:	goto yy98;
			}
yy202:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy203;
			}
yy203:
// 304 "scanner.re"
			{
			token->opcode = XX_T_ISSET;
			s->active_char += sizeof("isset")-1;
			return 0;
		}
// 2716 "scanner.c"
yy204:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy216;
			default:	goto yy98;
			}
yy205:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy206;
			}
yy206:
// 160 "scanner.re"
			{
			s->active_char += sizeof("int")-1;
			token->opcode = XX_T_TYPE_INTEGER;
			return 0;
		}
// 2800 "scanner.c"
yy207:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy208;
			default:	goto yy98;
			}
yy208:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy209;
			default:	goto yy98;
			}
yy209:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy210;
			default:	goto yy98;
			}
yy210:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy211;
			default:	goto yy98;
			}
yy211:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy212;
			default:	goto yy98;
			}
yy212:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy213;
			default:	goto yy98;
			}
yy213:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy214;
			default:	goto yy98;
			}
yy214:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy215;
			}
yy215:
// 298 "scanner.re"
			{
			token->opcode = XX_T_INSTANCEOF;
			s->active_char += sizeof("instanceof")-1;
			return 0;
		}
// 2926 "scanner.c"
yy216:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy217;
			default:	goto yy98;
			}
yy217:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy218;
			default:	goto yy98;
			}
yy218:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy219;
			}
yy219:
// 124 "scanner.re"
			{
			s->active_char += sizeof("inline")-1;
			token->opcode = XX_T_INLINE;
			return 0;
		}
// 3017 "scanner.c"
yy220:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy227;
			case 'R':
			case 'r':	goto yy228;
			default:	goto yy98;
			}
yy221:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy222;
			default:	goto yy98;
			}
yy222:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy223;
			default:	goto yy98;
			}
yy223:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy224;
			default:	goto yy98;
			}
yy224:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy225;
			default:	goto yy98;
			}
yy225:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy226;
			}
yy226:
// 328 "scanner.re"
			{
			token->opcode = XX_T_SWITCH;
			s->active_char += sizeof("switch")-1;
			return 0;
		}
// 3131 "scanner.c"
yy227:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy233;
			default:	goto yy98;
			}
yy228:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy229;
			default:	goto yy98;
			}
yy229:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy230;
			default:	goto yy98;
			}
yy230:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy231;
			default:	goto yy98;
			}
yy231:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy232;
			}
yy232:
// 220 "scanner.re"
			{
			s->active_char += sizeof("string")-1;
			token->opcode = XX_T_TYPE_STRING;
			return 0;
		}
// 3236 "scanner.c"
yy233:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy234;
			default:	goto yy98;
			}
yy234:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy235;
			default:	goto yy98;
			}
yy235:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy236;
			}
yy236:
// 118 "scanner.re"
			{
			s->active_char += sizeof("static")-1;
			token->opcode = XX_T_STATIC;
			return 0;
		}
// 3327 "scanner.c"
yy237:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy245;
			case 'O':
			case 'o':	goto yy244;
			default:	goto yy98;
			}
yy238:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy239;
			default:	goto yy98;
			}
yy239:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy240;
			default:	goto yy98;
			}
yy240:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy241;
			default:	goto yy98;
			}
yy241:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy242;
			default:	goto yy98;
			}
yy242:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy243;
			}
yy243:
// 100 "scanner.re"
			{
			s->active_char += sizeof("public")-1;
			token->opcode = XX_T_PUBLIC;
			return 0;
		}
// 3441 "scanner.c"
yy244:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy251;
			default:	goto yy98;
			}
yy245:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'V':
			case 'v':	goto yy246;
			default:	goto yy98;
			}
yy246:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy247;
			default:	goto yy98;
			}
yy247:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy248;
			default:	goto yy98;
			}
yy248:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy249;
			default:	goto yy98;
			}
yy249:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy250;
			}
yy250:
// 112 "scanner.re"
			{
			s->active_char += sizeof("private")-1;
			token->opcode = XX_T_PRIVATE;
			return 0;
		}
// 3553 "scanner.c"
yy251:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy252;
			default:	goto yy98;
			}
yy252:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy253;
			default:	goto yy98;
			}
yy253:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy254;
			default:	goto yy98;
			}
yy254:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy255;
			default:	goto yy98;
			}
yy255:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy256;
			default:	goto yy98;
			}
yy256:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy257;
			}
yy257:
// 106 "scanner.re"
			{
			s->active_char += sizeof("protected")-1;
			token->opcode = XX_T_PROTECTED;
			return 0;
		}
// 3665 "scanner.c"
yy258:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy270;
			default:	goto yy98;
			}
yy259:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy267;
			default:	goto yy98;
			}
yy260:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy261;
			default:	goto yy98;
			}
yy261:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy262;
			default:	goto yy98;
			}
yy262:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy263;
			default:	goto yy98;
			}
yy263:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy264;
			default:	goto yy98;
			}
yy264:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy265;
			default:	goto yy98;
			}
yy265:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy266;
			}
yy266:
// 94 "scanner.re"
			{
			s->active_char += sizeof("extends")-1;
			token->opcode = XX_T_EXTENDS;
			return 0;
		}
// 3791 "scanner.c"
yy267:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy268;
			default:	goto yy98;
			}
yy268:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy269;
			}
yy269:
// 238 "scanner.re"
			{
			s->active_char += sizeof("else")-1;
			token->opcode = XX_T_ELSE;
			return 0;
		}
// 3875 "scanner.c"
yy270:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy271;
			default:	goto yy98;
			}
yy271:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy272;
			}
yy272:
// 148 "scanner.re"
			{
			s->active_char += sizeof("echo")-1;
			token->opcode = XX_T_ECHO;
			return 0;
		}
// 3959 "scanner.c"
yy273:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy294;
			default:	goto yy98;
			}
yy274:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy291;
			default:	goto yy98;
			}
yy275:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy287;
			default:	goto yy98;
			}
yy276:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy277;
			default:	goto yy98;
			}
yy277:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy278;
			case 'T':
			case 't':	goto yy279;
			default:	goto yy98;
			}
yy278:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy285;
			default:	goto yy98;
			}
yy279:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy280;
			default:	goto yy98;
			}
yy280:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy281;
			default:	goto yy98;
			}
yy281:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy282;
			default:	goto yy98;
			}
yy282:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy283;
			default:	goto yy98;
			}
yy283:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy284;
			}
yy284:
// 286 "scanner.re"
			{
			token->opcode = XX_T_CONTINUE;
			s->active_char += sizeof("continue")-1;
			return 0;
		}
// 4108 "scanner.c"
yy285:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy286;
			}
yy286:
// 154 "scanner.re"
			{
			s->active_char += sizeof("const")-1;
			token->opcode = XX_T_CONST;
			return 0;
		}
// 4185 "scanner.c"
yy287:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy288;
			default:	goto yy98;
			}
yy288:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy289;
			default:	goto yy98;
			}
yy289:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy290;
			}
yy290:
// 88 "scanner.re"
			{
			s->active_char += sizeof("class")-1;
			token->opcode = XX_T_CLASS;
			return 0;
		}
// 4276 "scanner.c"
yy291:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy292;
			default:	goto yy98;
			}
yy292:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy293;
			}
yy293:
// 184 "scanner.re"
			{
			s->active_char += sizeof("char")-1;
			token->opcode = XX_T_TYPE_CHAR;
			return 0;
		}
// 4360 "scanner.c"
yy294:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy295;
			default:	goto yy98;
			}
yy295:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy296;
			}
yy296:
// 334 "scanner.re"
			{
			token->opcode = XX_T_CASE;
			s->active_char += sizeof("case")-1;
			return 0;
		}
// 4444 "scanner.c"
yy297:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy298;
			default:	goto yy98;
			}
yy298:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy299;
			default:	goto yy98;
			}
yy299:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy300;
			default:	goto yy98;
			}
yy300:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy301;
			default:	goto yy98;
			}
yy301:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy302;
			default:	goto yy98;
			}
yy302:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy303;
			default:	goto yy98;
			}
yy303:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy304;
			}
yy304:
// 82 "scanner.re"
			{
			s->active_char += sizeof("abstract")-1;
			token->opcode = XX_T_ABSTRACT;
			return 0;
		}
// 4563 "scanner.c"
yy305:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy316;
			default:	goto yy98;
			}
yy306:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy313;
			default:	goto yy98;
			}
yy307:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy308;
			default:	goto yy98;
			}
yy308:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy309;
			default:	goto yy98;
			}
yy309:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy310;
			default:	goto yy98;
			}
yy310:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy311;
			default:	goto yy98;
			}
yy311:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy312;
			}
yy312:
// 292 "scanner.re"
			{
			token->opcode = XX_T_TYPEOF;
			s->active_char += sizeof("typeof")-1;
			return 0;
		}
// 4682 "scanner.c"
yy313:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy314;
			default:	goto yy98;
			}
yy314:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy315;
			}
yy315:
// 70 "scanner.re"
			{
			s->active_char += sizeof("true")-1;
			token->opcode = XX_T_TRUE;
			return 0;
		}
// 4766 "scanner.c"
yy316:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy317;
			default:	goto yy98;
			}
yy317:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'W':
			case 'w':	goto yy318;
			default:	goto yy98;
			}
yy318:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy319;
			}
yy319:
// 316 "scanner.re"
			{
			token->opcode = XX_T_THROW;
			s->active_char += sizeof("throw")-1;
			return 0;
		}
// 4857 "scanner.c"
yy320:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy344;
			default:	goto yy98;
			}
yy321:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy340;
			default:	goto yy98;
			}
yy322:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy336;
			default:	goto yy98;
			}
yy323:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy324;
			}
yy324:
// 136 "scanner.re"
			{
			s->active_char += sizeof("fn")-1;
			token->opcode = XX_T_FUNCTION;
			return 0;
		}
// 4955 "scanner.c"
yy325:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy334;
			default:	goto yy98;
			}
yy326:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy327;
			default:	goto yy98;
			}
yy327:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy328;
			default:	goto yy98;
			}
yy328:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy329;
			default:	goto yy98;
			}
yy329:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy330;
			default:	goto yy98;
			}
yy330:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy331;
			default:	goto yy98;
			}
yy331:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy332;
			default:	goto yy98;
			}
yy332:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy333;
			}
yy333:
// 130 "scanner.re"
			{
			s->active_char += sizeof("function")-1;
			token->opcode = XX_T_FUNCTION;
			return 0;
		}
// 5081 "scanner.c"
yy334:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy335;
			}
yy335:
// 250 "scanner.re"
			{
			s->active_char += sizeof("for")-1;
			token->opcode = XX_T_FOR;
			return 0;
		}
// 5158 "scanner.c"
yy336:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy337;
			default:	goto yy98;
			}
yy337:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy338;
			default:	goto yy98;
			}
yy338:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy339;
			}
yy339:
// 202 "scanner.re"
			{
			s->active_char += sizeof("float")-1;
			token->opcode = XX_T_TYPE_DOUBLE;
			return 0;
		}
// 5249 "scanner.c"
yy340:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy341;
			default:	goto yy98;
			}
yy341:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy342;
			default:	goto yy98;
			}
yy342:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy343;
			}
yy343:
// 322 "scanner.re"
			{
			token->opcode = XX_T_FETCH;
			s->active_char += sizeof("fetch")-1;
			return 0;
		}
// 5340 "scanner.c"
yy344:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy345;
			default:	goto yy98;
			}
yy345:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy346;
			default:	goto yy98;
			}
yy346:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy347;
			}
yy347:
// 64 "scanner.re"
			{
			s->active_char += sizeof("false")-1;
			token->opcode = XX_T_FALSE;
			return 0;
		}
// 5431 "scanner.c"
yy348:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy356;
			default:	goto yy98;
			}
yy349:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'W':
			case 'w':	goto yy354;
			default:	goto yy98;
			}
yy350:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy351;
			default:	goto yy98;
			}
yy351:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy352;
			default:	goto yy98;
			}
yy352:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy353;
			}
yy353:
// 58 "scanner.re"
			{
			s->active_char += sizeof("null")-1;
			token->opcode = XX_T_NULL;
			return 0;
		}
// 5536 "scanner.c"
yy354:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy355;
			}
yy355:
// 262 "scanner.re"
			{
			s->active_char += sizeof("new")-1;
			token->opcode = XX_T_NEW;
			return 0;
		}
// 5613 "scanner.c"
yy356:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy357;
			default:	goto yy98;
			}
yy357:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy358;
			default:	goto yy98;
			}
yy358:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy359;
			default:	goto yy98;
			}
yy359:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy360;
			default:	goto yy98;
			}
yy360:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy361;
			default:	goto yy98;
			}
yy361:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy362;
			default:	goto yy98;
			}
yy362:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy97;
			default:	goto yy363;
			}
yy363:
// 76 "scanner.re"
			{
			s->active_char += sizeof("namespace")-1;
			token->opcode = XX_T_NAMESPACE;
			return 0;
		}
// 5732 "scanner.c"
yy364:
			yych = *++YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy367;
			default:	goto yy111;
			}
yy365:
			yyaccept = 0;
			YYMARKER = ++YYCURSOR;
			yych = *YYCURSOR;
yy366:
			switch (yych) {
			case '.':	goto yy364;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy365;
			default:	goto yy5;
			}
yy367:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy367;
			default:	goto yy369;
			}
yy369:
// 49 "scanner.re"
			{
			token->opcode = XX_T_DOUBLE;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 5793 "scanner.c"
yy370:
			++YYCURSOR;
// 577 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_DECR;
			return 0;
		}
// 5802 "scanner.c"
yy372:
			++YYCURSOR;
// 547 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_ARROW;
			return 0;
		}
// 5811 "scanner.c"
yy374:
			++YYCURSOR;
// 475 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SUBASSIGN;
			return 0;
		}
// 5820 "scanner.c"
		}
// 624 "scanner.re"

	}

	return status;
}
