/* Generated by re2c 0.13.5 on Sat Aug 31 19:33:31 2013 */
// 1 "scanner.re"

/*
 +----------------------------------------------------------------------+
 | Zephir Language                                                      |
 +----------------------------------------------------------------------+
 | Copyright (c) 2013 Zephir Team                                       |
 +----------------------------------------------------------------------+
 | This source file is subject to version 1.0 of the Zephir license,    |
 | that is bundled with this package in the file LICENSE, and is        |
 | available through the world-wide-web at the following url:           |
 | http://www.zephir-lang.com/license                                   |
 |                                                                      |
 | If you did not receive a copy of the Zephir license and are unable   |
 | to obtain it through the world-wide-web, please send a note to       |
 | license@zephir-lang.com so we can mail you a copy immediately.       |
 +----------------------------------------------------------------------+
*/

#include "string.h"
#include "scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int xx_get_token(xx_scanner_state *s, xx_scanner_token *token) {

	char next, *q = YYCURSOR, *start = YYCURSOR;
	int status = XX_SCANNER_RETCODE_IMPOSSIBLE;
	int is_constant = 0, j;

	while (XX_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
// 39 "scanner.c"
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy68;
			case '\t':
			case '\r':
			case ' ':	goto yy64;
			case '\n':	goto yy66;
			case '!':	goto yy43;
			case '"':	goto yy25;
			case '&':	goto yy45;
			case '\'':	goto yy23;
			case '(':	goto yy29;
			case ')':	goto yy31;
			case '*':	goto yy51;
			case '+':	goto yy49;
			case ',':	goto yy62;
			case '-':	goto yy2;
			case '.':	goto yy52;
			case '/':	goto yy26;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy4;
			case ':':	goto yy58;
			case ';':	goto yy60;
			case '<':	goto yy54;
			case '=':	goto yy47;
			case '>':	goto yy56;
			case '@':	goto yy41;
			case 'A':
			case 'a':	goto yy10;
			case 'B':
			case 'b':	goto yy19;
			case 'C':
			case 'c':	goto yy11;
			case 'D':
			case 'd':	goto yy18;
			case 'E':
			case 'e':	goto yy12;
			case 'F':
			case 'f':	goto yy8;
			case 'G':
			case 'H':
			case 'J':
			case 'K':
			case 'M':
			case 'O':
			case 'Q':
			case 'X':
			case 'Y':
			case 'Z':
			case 'g':
			case 'h':
			case 'j':
			case 'k':
			case 'm':
			case 'o':
			case 'q':
			case 'x':
			case 'y':
			case 'z':	goto yy28;
			case 'I':
			case 'i':	goto yy15;
			case 'L':
			case 'l':	goto yy16;
			case 'N':
			case 'n':	goto yy6;
			case 'P':
			case 'p':	goto yy13;
			case 'R':
			case 'r':	goto yy22;
			case 'S':
			case 's':	goto yy14;
			case 'T':
			case 't':	goto yy9;
			case 'U':
			case 'u':	goto yy17;
			case 'V':
			case 'v':	goto yy20;
			case 'W':
			case 'w':	goto yy21;
			case '[':	goto yy37;
			case '\\':
			case '_':	goto yy27;
			case ']':	goto yy39;
			case '{':	goto yy33;
			case '|':	goto yy46;
			case '}':	goto yy35;
			default:	goto yy70;
			}
yy2:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '-':	goto yy378;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy373;
			case '=':	goto yy382;
			case '>':	goto yy380;
			default:	goto yy3;
			}
yy3:
// 618 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SUB;
			return 0;
		}
// 165 "scanner.c"
yy4:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			goto yy374;
yy5:
// 40 "scanner.re"
			{
			token->opcode = XX_T_INTEGER;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 180 "scanner.c"
yy6:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case 'A':
			case 'a':	goto yy356;
			case 'E':
			case 'e':	goto yy357;
			case 'U':
			case 'u':	goto yy358;
			default:	goto yy100;
			}
yy7:
// 413 "scanner.re"
			{

			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;

			if (!memcmp(token->value, "_GET", sizeof("_GET")-1)) {
				token->opcode = XX_T_IDENTIFIER;
				return 0;
			}

			if (!memcmp(token->value, "_POST", sizeof("_POST")-1)) {
				token->opcode = XX_T_IDENTIFIER;
				return 0;
			}

			if (!memcmp(token->value, "_SERVER", sizeof("_SERVER")-1)) {
				token->opcode = XX_T_IDENTIFIER;
				return 0;
			}

			is_constant = 1;
			for (j = 0; j < token->len; j++) {
				if (!((token->value[j] >= 'A' && token->value[j] <= 'Z') || (token->value[j] >= '0' && token->value[j] <= '9') || token->value[j] == '_')) {
					is_constant = 0;
					break;
				}
			};
			if (is_constant) {
				token->opcode = XX_T_CONSTANT;
			} else {
				token->opcode = XX_T_IDENTIFIER;
			}
			return 0;
		}
// 230 "scanner.c"
yy8:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy323;
			case 'E':
			case 'e':	goto yy324;
			case 'I':
			case 'i':	goto yy325;
			case 'L':
			case 'l':	goto yy326;
			case 'N':
			case 'n':	goto yy327;
			case 'O':
			case 'o':	goto yy329;
			case 'U':
			case 'u':	goto yy330;
			default:	goto yy100;
			}
yy9:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy308;
			case 'R':
			case 'r':	goto yy309;
			case 'Y':
			case 'y':	goto yy310;
			default:	goto yy100;
			}
yy10:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy300;
			default:	goto yy100;
			}
yy11:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy276;
			case 'H':
			case 'h':	goto yy277;
			case 'L':
			case 'l':	goto yy278;
			case 'O':
			case 'o':	goto yy279;
			default:	goto yy100;
			}
yy12:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy261;
			case 'L':
			case 'l':	goto yy262;
			case 'X':
			case 'x':	goto yy263;
			default:	goto yy100;
			}
yy13:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy240;
			case 'U':
			case 'u':	goto yy241;
			default:	goto yy100;
			}
yy14:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy223;
			case 'W':
			case 'w':	goto yy224;
			default:	goto yy100;
			}
yy15:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy198;
			case 'N':
			case 'n':	goto yy200;
			case 'S':
			case 's':	goto yy202;
			default:	goto yy100;
			}
yy16:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy188;
			case 'O':
			case 'o':	goto yy189;
			default:	goto yy100;
			}
yy17:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy169;
			case 'I':
			case 'i':	goto yy170;
			case 'L':
			case 'l':	goto yy171;
			case 'N':
			case 'n':	goto yy172;
			default:	goto yy100;
			}
yy18:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy155;
			case 'O':
			case 'o':	goto yy156;
			default:	goto yy100;
			}
yy19:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy142;
			case 'R':
			case 'r':	goto yy143;
			default:	goto yy100;
			}
yy20:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy139;
			default:	goto yy100;
			}
yy21:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy134;
			default:	goto yy100;
			}
yy22:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy122;
			default:	goto yy100;
			}
yy23:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych >= 0x01) goto yy118;
yy24:
// 672 "scanner.re"
			{
			status = XX_SCANNER_RETCODE_ERR;
			break;
		}
// 392 "scanner.c"
yy25:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy24;
			goto yy112;
yy26:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case '*':	goto yy106;
			case '/':	goto yy103;
			case '=':	goto yy101;
			default:	goto yy24;
			}
yy27:
			yych = *++YYCURSOR;
			goto yy100;
yy28:
			yych = *++YYCURSOR;
			goto yy100;
yy29:
			++YYCURSOR;
// 450 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_PARENTHESES_OPEN;
			return 0;
		}
// 421 "scanner.c"
yy31:
			++YYCURSOR;
// 456 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_PARENTHESES_CLOSE;
			return 0;
		}
// 430 "scanner.c"
yy33:
			++YYCURSOR;
// 462 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_BRACKET_OPEN;
			return 0;
		}
// 439 "scanner.c"
yy35:
			++YYCURSOR;
// 468 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_BRACKET_CLOSE;
			return 0;
		}
// 448 "scanner.c"
yy37:
			++YYCURSOR;
// 474 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SBRACKET_OPEN;
			return 0;
		}
// 457 "scanner.c"
yy39:
			++YYCURSOR;
// 480 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SBRACKET_CLOSE;
			return 0;
		}
// 466 "scanner.c"
yy41:
			++YYCURSOR;
// 486 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_AT;
			return 0;
		}
// 475 "scanner.c"
yy43:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy95;
			default:	goto yy44;
			}
yy44:
// 492 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_NOT;
			return 0;
		}
// 489 "scanner.c"
yy45:
			yych = *++YYCURSOR;
			switch (yych) {
			case '&':	goto yy93;
			default:	goto yy24;
			}
yy46:
			yych = *++YYCURSOR;
			switch (yych) {
			case '|':	goto yy91;
			default:	goto yy24;
			}
yy47:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy87;
			default:	goto yy48;
			}
yy48:
// 510 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_ASSIGN;
			return 0;
		}
// 515 "scanner.c"
yy49:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '+':	goto yy83;
			case '=':	goto yy85;
			default:	goto yy50;
			}
yy50:
// 612 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_ADD;
			return 0;
		}
// 530 "scanner.c"
yy51:
			yych = *++YYCURSOR;
			switch (yych) {
			case '=':	goto yy81;
			default:	goto yy24;
			}
yy52:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy79;
			default:	goto yy53;
			}
yy53:
// 606 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_DOT;
			return 0;
		}
// 550 "scanner.c"
yy54:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy77;
			default:	goto yy55;
			}
yy55:
// 582 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_LESS;
			return 0;
		}
// 564 "scanner.c"
yy56:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy75;
			default:	goto yy57;
			}
yy57:
// 588 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_GREATER;
			return 0;
		}
// 578 "scanner.c"
yy58:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case ':':	goto yy73;
			default:	goto yy59;
			}
yy59:
// 636 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_COLON;
			return 0;
		}
// 592 "scanner.c"
yy60:
			++YYCURSOR;
// 642 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_DOTCOMMA;
			return 0;
		}
// 601 "scanner.c"
yy62:
			++YYCURSOR;
// 648 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_COMMA;
			return 0;
		}
// 610 "scanner.c"
yy64:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy72;
yy65:
// 654 "scanner.re"
			{
			s->active_char += (YYCURSOR - start);
			token->opcode = XX_T_IGNORE;
			return 0;
		}
// 622 "scanner.c"
yy66:
			++YYCURSOR;
// 660 "scanner.re"
			{
			s->active_line++;
			s->active_char = 0;
			token->opcode = XX_T_IGNORE;
			return 0;
		}
// 632 "scanner.c"
yy68:
			++YYCURSOR;
// 667 "scanner.re"
			{
			status = XX_SCANNER_RETCODE_EOF;
			break;
		}
// 640 "scanner.c"
yy70:
			yych = *++YYCURSOR;
			goto yy24;
yy71:
			++YYCURSOR;
			yych = *YYCURSOR;
yy72:
			switch (yych) {
			case '\t':
			case '\r':
			case ' ':	goto yy71;
			default:	goto yy65;
			}
yy73:
			++YYCURSOR;
// 600 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_DOUBLECOLON;
			return 0;
		}
// 662 "scanner.c"
yy75:
			++YYCURSOR;
// 576 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_GREATEREQUAL;
			return 0;
		}
// 671 "scanner.c"
yy77:
			++YYCURSOR;
// 570 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_LESSEQUAL;
			return 0;
		}
// 680 "scanner.c"
yy79:
			++YYCURSOR;
// 540 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_CONCATASSIGN;
			return 0;
		}
// 689 "scanner.c"
yy81:
			++YYCURSOR;
// 528 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_MULASSIGN;
			return 0;
		}
// 698 "scanner.c"
yy83:
			++YYCURSOR;
// 624 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_INCR;
			return 0;
		}
// 707 "scanner.c"
yy85:
			++YYCURSOR;
// 516 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_ADDASSIGN;
			return 0;
		}
// 716 "scanner.c"
yy87:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy89;
			default:	goto yy88;
			}
yy88:
// 546 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_EQUALS;
			return 0;
		}
// 730 "scanner.c"
yy89:
			++YYCURSOR;
// 558 "scanner.re"
			{
			s->active_char += 3;
			token->opcode = XX_T_IDENTICAL;
			return 0;
		}
// 739 "scanner.c"
yy91:
			++YYCURSOR;
// 504 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_OR;
			return 0;
		}
// 748 "scanner.c"
yy93:
			++YYCURSOR;
// 498 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_AND;
			return 0;
		}
// 757 "scanner.c"
yy95:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '=':	goto yy97;
			default:	goto yy96;
			}
yy96:
// 552 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_NOTEQUALS;
			return 0;
		}
// 771 "scanner.c"
yy97:
			++YYCURSOR;
// 564 "scanner.re"
			{
			s->active_char += 3;
			token->opcode = XX_T_NOTIDENTICAL;
			return 0;
		}
// 780 "scanner.c"
yy99:
			++YYCURSOR;
			yych = *YYCURSOR;
yy100:
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy7;
			}
yy101:
			++YYCURSOR;
// 534 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_DIVASSIGN;
			return 0;
		}
// 860 "scanner.c"
yy103:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':
			case '\r':	goto yy105;
			default:	goto yy103;
			}
yy105:
// 392 "scanner.re"
			{
			token->opcode = XX_T_COMMENT;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			{
				int k, ch = s->active_char;
				for (k = 0; k < (token->len - 1); k++) {
					if (token->value[k] == '\n') {
						ch = 1;
						s->active_line++;
					} else {
						ch++;
					}
				}
				s->active_char = ch;
			}
			q = YYCURSOR;
			return 0;
		}
// 890 "scanner.c"
yy106:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':	goto yy108;
			default:	goto yy106;
			}
yy108:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':	goto yy108;
			case '/':	goto yy110;
			default:	goto yy106;
			}
yy110:
			yych = *++YYCURSOR;
			goto yy105;
yy111:
			++YYCURSOR;
			yych = *YYCURSOR;
yy112:
			switch (yych) {
			case 0x00:	goto yy113;
			case '"':	goto yy115;
			case '\\':	goto yy114;
			default:	goto yy111;
			}
yy113:
			YYCURSOR = YYMARKER;
			switch (yyaccept) {
			case 0: 	goto yy5;
			case 1: 	goto yy24;
			}
yy114:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy113;
			default:	goto yy111;
			}
yy115:
			++YYCURSOR;
// 382 "scanner.re"
			{
			token->opcode = XX_T_STRING;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 943 "scanner.c"
yy117:
			++YYCURSOR;
			yych = *YYCURSOR;
yy118:
			switch (yych) {
			case 0x00:	goto yy113;
			case '\'':	goto yy120;
			case '\\':	goto yy119;
			default:	goto yy117;
			}
yy119:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\n':	goto yy113;
			default:	goto yy117;
			}
yy120:
			++YYCURSOR;
// 372 "scanner.re"
			{
			token->opcode = XX_T_SCHAR;
			token->value = strndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 972 "scanner.c"
yy122:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy123;
			case 'V':
			case 'v':	goto yy124;
			default:	goto yy100;
			}
yy123:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy130;
			default:	goto yy100;
			}
yy124:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy125;
			default:	goto yy100;
			}
yy125:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy126;
			default:	goto yy100;
			}
yy126:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy127;
			default:	goto yy100;
			}
yy127:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy128;
			default:	goto yy100;
			}
yy128:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy129;
			}
yy129:
// 365 "scanner.re"
			{
			token->opcode = XX_T_REVERSE;
			s->active_char += sizeof("reverse")-1;
			return 0;
		}
// 1093 "scanner.c"
yy130:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy131;
			default:	goto yy100;
			}
yy131:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy132;
			default:	goto yy100;
			}
yy132:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy133;
			}
yy133:
// 287 "scanner.re"
			{
			s->active_char += sizeof("return")-1;
			token->opcode = XX_T_RETURN;
			return 0;
		}
// 1184 "scanner.c"
yy134:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy135;
			default:	goto yy100;
			}
yy135:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy136;
			default:	goto yy100;
			}
yy136:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy137;
			default:	goto yy100;
			}
yy137:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy138;
			}
yy138:
// 263 "scanner.re"
			{
			s->active_char += sizeof("while")-1;
			token->opcode = XX_T_WHILE;
			return 0;
		}
// 1282 "scanner.c"
yy139:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy140;
			default:	goto yy100;
			}
yy140:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy141;
			}
yy141:
// 239 "scanner.re"
			{
			s->active_char += sizeof("var")-1;
			token->opcode = XX_T_TYPE_VAR;
			return 0;
		}
// 1366 "scanner.c"
yy142:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy148;
			default:	goto yy100;
			}
yy143:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy144;
			default:	goto yy100;
			}
yy144:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy145;
			default:	goto yy100;
			}
yy145:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'K':
			case 'k':	goto yy146;
			default:	goto yy100;
			}
yy146:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy147;
			}
yy147:
// 299 "scanner.re"
			{
			token->opcode = XX_T_BREAK;
			s->active_char += sizeof("break")-1;
			return 0;
		}
// 1471 "scanner.c"
yy148:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy149;
			default:	goto yy100;
			}
yy149:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			case 'E':
			case 'e':	goto yy151;
			default:	goto yy150;
			}
yy150:
// 221 "scanner.re"
			{
			s->active_char += sizeof("bool")-1;
			token->opcode = XX_T_TYPE_BOOL;
			return 0;
		}
// 1555 "scanner.c"
yy151:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy152;
			default:	goto yy100;
			}
yy152:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy153;
			default:	goto yy100;
			}
yy153:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy154;
			}
yy154:
// 227 "scanner.re"
			{
			s->active_char += sizeof("boolean")-1;
			token->opcode = XX_T_TYPE_BOOL;
			return 0;
		}
// 1646 "scanner.c"
yy155:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy163;
			default:	goto yy100;
			}
yy156:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			case 'U':
			case 'u':	goto yy158;
			default:	goto yy157;
			}
yy157:
// 257 "scanner.re"
			{
			s->active_char += sizeof("do")-1;
			token->opcode = XX_T_DO;
			return 0;
		}
// 1730 "scanner.c"
yy158:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy159;
			default:	goto yy100;
			}
yy159:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy160;
			default:	goto yy100;
			}
yy160:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy161;
			default:	goto yy100;
			}
yy161:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy162;
			}
yy162:
// 209 "scanner.re"
			{
			s->active_char += sizeof("double")-1;
			token->opcode = XX_T_TYPE_DOUBLE;
			return 0;
		}
// 1828 "scanner.c"
yy163:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy164;
			default:	goto yy100;
			}
yy164:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy165;
			default:	goto yy100;
			}
yy165:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy166;
			default:	goto yy100;
			}
yy166:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy167;
			default:	goto yy100;
			}
yy167:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy168;
			}
yy168:
// 359 "scanner.re"
			{
			token->opcode = XX_T_DEFAULT;
			s->active_char += sizeof("default")-1;
			return 0;
		}
// 1933 "scanner.c"
yy169:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy184;
			default:	goto yy100;
			}
yy170:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy181;
			default:	goto yy100;
			}
yy171:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy177;
			default:	goto yy100;
			}
yy172:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy173;
			default:	goto yy100;
			}
yy173:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy174;
			default:	goto yy100;
			}
yy174:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy175;
			default:	goto yy100;
			}
yy175:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy176;
			}
yy176:
// 329 "scanner.re"
			{
			token->opcode = XX_T_UNSET;
			s->active_char += sizeof("unset")-1;
			return 0;
		}
// 2052 "scanner.c"
yy177:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy178;
			default:	goto yy100;
			}
yy178:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy179;
			default:	goto yy100;
			}
yy179:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy180;
			}
yy180:
// 191 "scanner.re"
			{
			s->active_char += sizeof("ulong")-1;
			token->opcode = XX_T_TYPE_ULONG;
			return 0;
		}
// 2143 "scanner.c"
yy181:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy182;
			default:	goto yy100;
			}
yy182:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy183;
			}
yy183:
// 179 "scanner.re"
			{
			s->active_char += sizeof("uint")-1;
			token->opcode = XX_T_TYPE_UINTEGER;
			return 0;
		}
// 2227 "scanner.c"
yy184:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy185;
			default:	goto yy100;
			}
yy185:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy186;
			default:	goto yy100;
			}
yy186:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy187;
			}
yy187:
// 203 "scanner.re"
			{
			s->active_char += sizeof("uchar")-1;
			token->opcode = XX_T_TYPE_UCHAR;
			return 0;
		}
// 2318 "scanner.c"
yy188:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy196;
			default:	goto yy100;
			}
yy189:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy190;
			case 'O':
			case 'o':	goto yy191;
			default:	goto yy100;
			}
yy190:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy194;
			default:	goto yy100;
			}
yy191:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy192;
			default:	goto yy100;
			}
yy192:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy193;
			}
yy193:
// 293 "scanner.re"
			{
			token->opcode = XX_T_LOOP;
			s->active_char += sizeof("loop")-1;
			return 0;
		}
// 2425 "scanner.c"
yy194:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy195;
			}
yy195:
// 185 "scanner.re"
			{
			s->active_char += sizeof("long")-1;
			token->opcode = XX_T_TYPE_LONG;
			return 0;
		}
// 2502 "scanner.c"
yy196:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy197;
			}
yy197:
// 155 "scanner.re"
			{
			s->active_char += sizeof("let")-1;
			token->opcode = XX_T_LET;
			return 0;
		}
// 2579 "scanner.c"
yy198:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy199;
			}
yy199:
// 245 "scanner.re"
			{
			s->active_char += sizeof("if")-1;
			token->opcode = XX_T_IF;
			return 0;
		}
// 2656 "scanner.c"
yy200:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			case 'L':
			case 'l':	goto yy207;
			case 'S':
			case 's':	goto yy210;
			case 'T':
			case 't':	goto yy208;
			default:	goto yy201;
			}
yy201:
// 275 "scanner.re"
			{
			s->active_char += sizeof("in")-1;
			token->opcode = XX_T_IN;
			return 0;
		}
// 2733 "scanner.c"
yy202:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy203;
			default:	goto yy100;
			}
yy203:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy204;
			default:	goto yy100;
			}
yy204:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy205;
			default:	goto yy100;
			}
yy205:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy206;
			}
yy206:
// 323 "scanner.re"
			{
			token->opcode = XX_T_ISSET;
			s->active_char += sizeof("isset")-1;
			return 0;
		}
// 2831 "scanner.c"
yy207:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy219;
			default:	goto yy100;
			}
yy208:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy209;
			}
yy209:
// 173 "scanner.re"
			{
			s->active_char += sizeof("int")-1;
			token->opcode = XX_T_TYPE_INTEGER;
			return 0;
		}
// 2915 "scanner.c"
yy210:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy211;
			default:	goto yy100;
			}
yy211:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy212;
			default:	goto yy100;
			}
yy212:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy213;
			default:	goto yy100;
			}
yy213:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy214;
			default:	goto yy100;
			}
yy214:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy215;
			default:	goto yy100;
			}
yy215:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy216;
			default:	goto yy100;
			}
yy216:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy217;
			default:	goto yy100;
			}
yy217:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy218;
			}
yy218:
// 317 "scanner.re"
			{
			token->opcode = XX_T_INSTANCEOF;
			s->active_char += sizeof("instanceof")-1;
			return 0;
		}
// 3041 "scanner.c"
yy219:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy220;
			default:	goto yy100;
			}
yy220:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy221;
			default:	goto yy100;
			}
yy221:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy222;
			}
yy222:
// 125 "scanner.re"
			{
			s->active_char += sizeof("inline")-1;
			token->opcode = XX_T_INLINE;
			return 0;
		}
// 3132 "scanner.c"
yy223:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy230;
			case 'R':
			case 'r':	goto yy231;
			default:	goto yy100;
			}
yy224:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy225;
			default:	goto yy100;
			}
yy225:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy226;
			default:	goto yy100;
			}
yy226:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy227;
			default:	goto yy100;
			}
yy227:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy228;
			default:	goto yy100;
			}
yy228:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy229;
			}
yy229:
// 347 "scanner.re"
			{
			token->opcode = XX_T_SWITCH;
			s->active_char += sizeof("switch")-1;
			return 0;
		}
// 3246 "scanner.c"
yy230:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy236;
			default:	goto yy100;
			}
yy231:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy232;
			default:	goto yy100;
			}
yy232:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy233;
			default:	goto yy100;
			}
yy233:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy234;
			default:	goto yy100;
			}
yy234:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy235;
			}
yy235:
// 233 "scanner.re"
			{
			s->active_char += sizeof("string")-1;
			token->opcode = XX_T_TYPE_STRING;
			return 0;
		}
// 3351 "scanner.c"
yy236:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy237;
			default:	goto yy100;
			}
yy237:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy238;
			default:	goto yy100;
			}
yy238:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy239;
			}
yy239:
// 119 "scanner.re"
			{
			s->active_char += sizeof("static")-1;
			token->opcode = XX_T_STATIC;
			return 0;
		}
// 3442 "scanner.c"
yy240:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy248;
			case 'O':
			case 'o':	goto yy247;
			default:	goto yy100;
			}
yy241:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy242;
			default:	goto yy100;
			}
yy242:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy243;
			default:	goto yy100;
			}
yy243:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy244;
			default:	goto yy100;
			}
yy244:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy245;
			default:	goto yy100;
			}
yy245:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy246;
			}
yy246:
// 101 "scanner.re"
			{
			s->active_char += sizeof("public")-1;
			token->opcode = XX_T_PUBLIC;
			return 0;
		}
// 3556 "scanner.c"
yy247:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy254;
			default:	goto yy100;
			}
yy248:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'V':
			case 'v':	goto yy249;
			default:	goto yy100;
			}
yy249:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy250;
			default:	goto yy100;
			}
yy250:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy251;
			default:	goto yy100;
			}
yy251:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy252;
			default:	goto yy100;
			}
yy252:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy253;
			}
yy253:
// 113 "scanner.re"
			{
			s->active_char += sizeof("private")-1;
			token->opcode = XX_T_PRIVATE;
			return 0;
		}
// 3668 "scanner.c"
yy254:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy255;
			default:	goto yy100;
			}
yy255:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy256;
			default:	goto yy100;
			}
yy256:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy257;
			default:	goto yy100;
			}
yy257:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy258;
			default:	goto yy100;
			}
yy258:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy259;
			default:	goto yy100;
			}
yy259:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy260;
			}
yy260:
// 107 "scanner.re"
			{
			s->active_char += sizeof("protected")-1;
			token->opcode = XX_T_PROTECTED;
			return 0;
		}
// 3780 "scanner.c"
yy261:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy273;
			default:	goto yy100;
			}
yy262:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy270;
			default:	goto yy100;
			}
yy263:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy264;
			default:	goto yy100;
			}
yy264:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy265;
			default:	goto yy100;
			}
yy265:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy266;
			default:	goto yy100;
			}
yy266:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy267;
			default:	goto yy100;
			}
yy267:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy268;
			default:	goto yy100;
			}
yy268:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy269;
			}
yy269:
// 95 "scanner.re"
			{
			s->active_char += sizeof("extends")-1;
			token->opcode = XX_T_EXTENDS;
			return 0;
		}
// 3906 "scanner.c"
yy270:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy271;
			default:	goto yy100;
			}
yy271:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy272;
			}
yy272:
// 251 "scanner.re"
			{
			s->active_char += sizeof("else")-1;
			token->opcode = XX_T_ELSE;
			return 0;
		}
// 3990 "scanner.c"
yy273:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy274;
			default:	goto yy100;
			}
yy274:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy275;
			}
yy275:
// 161 "scanner.re"
			{
			s->active_char += sizeof("echo")-1;
			token->opcode = XX_T_ECHO;
			return 0;
		}
// 4074 "scanner.c"
yy276:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy297;
			default:	goto yy100;
			}
yy277:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy294;
			default:	goto yy100;
			}
yy278:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy290;
			default:	goto yy100;
			}
yy279:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy280;
			default:	goto yy100;
			}
yy280:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy281;
			case 'T':
			case 't':	goto yy282;
			default:	goto yy100;
			}
yy281:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy288;
			default:	goto yy100;
			}
yy282:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy283;
			default:	goto yy100;
			}
yy283:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy284;
			default:	goto yy100;
			}
yy284:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy285;
			default:	goto yy100;
			}
yy285:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy286;
			default:	goto yy100;
			}
yy286:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy287;
			}
yy287:
// 305 "scanner.re"
			{
			token->opcode = XX_T_CONTINUE;
			s->active_char += sizeof("continue")-1;
			return 0;
		}
// 4223 "scanner.c"
yy288:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy289;
			}
yy289:
// 167 "scanner.re"
			{
			s->active_char += sizeof("const")-1;
			token->opcode = XX_T_CONST;
			return 0;
		}
// 4300 "scanner.c"
yy290:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy291;
			default:	goto yy100;
			}
yy291:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy292;
			default:	goto yy100;
			}
yy292:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy293;
			}
yy293:
// 89 "scanner.re"
			{
			s->active_char += sizeof("class")-1;
			token->opcode = XX_T_CLASS;
			return 0;
		}
// 4391 "scanner.c"
yy294:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy295;
			default:	goto yy100;
			}
yy295:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy296;
			}
yy296:
// 197 "scanner.re"
			{
			s->active_char += sizeof("char")-1;
			token->opcode = XX_T_TYPE_CHAR;
			return 0;
		}
// 4475 "scanner.c"
yy297:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy298;
			default:	goto yy100;
			}
yy298:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy299;
			}
yy299:
// 353 "scanner.re"
			{
			token->opcode = XX_T_CASE;
			s->active_char += sizeof("case")-1;
			return 0;
		}
// 4559 "scanner.c"
yy300:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy301;
			default:	goto yy100;
			}
yy301:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy302;
			default:	goto yy100;
			}
yy302:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy303;
			default:	goto yy100;
			}
yy303:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy304;
			default:	goto yy100;
			}
yy304:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy305;
			default:	goto yy100;
			}
yy305:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy306;
			default:	goto yy100;
			}
yy306:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy307;
			}
yy307:
// 83 "scanner.re"
			{
			s->active_char += sizeof("abstract")-1;
			token->opcode = XX_T_ABSTRACT;
			return 0;
		}
// 4678 "scanner.c"
yy308:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy319;
			default:	goto yy100;
			}
yy309:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy316;
			default:	goto yy100;
			}
yy310:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy311;
			default:	goto yy100;
			}
yy311:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy312;
			default:	goto yy100;
			}
yy312:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy313;
			default:	goto yy100;
			}
yy313:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'F':
			case 'f':	goto yy314;
			default:	goto yy100;
			}
yy314:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy315;
			}
yy315:
// 311 "scanner.re"
			{
			token->opcode = XX_T_TYPEOF;
			s->active_char += sizeof("typeof")-1;
			return 0;
		}
// 4797 "scanner.c"
yy316:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy317;
			default:	goto yy100;
			}
yy317:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy318;
			}
yy318:
// 71 "scanner.re"
			{
			s->active_char += sizeof("true")-1;
			token->opcode = XX_T_TRUE;
			return 0;
		}
// 4881 "scanner.c"
yy319:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy320;
			default:	goto yy100;
			}
yy320:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'W':
			case 'w':	goto yy321;
			default:	goto yy100;
			}
yy321:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy322;
			}
yy322:
// 335 "scanner.re"
			{
			token->opcode = XX_T_THROW;
			s->active_char += sizeof("throw")-1;
			return 0;
		}
// 4972 "scanner.c"
yy323:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy352;
			default:	goto yy100;
			}
yy324:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy348;
			default:	goto yy100;
			}
yy325:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy344;
			default:	goto yy100;
			}
yy326:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy340;
			default:	goto yy100;
			}
yy327:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy328;
			}
yy328:
// 149 "scanner.re"
			{
			s->active_char += sizeof("fn")-1;
			token->opcode = XX_T_FUNCTION;
			return 0;
		}
// 5077 "scanner.c"
yy329:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy338;
			default:	goto yy100;
			}
yy330:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy331;
			default:	goto yy100;
			}
yy331:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy332;
			default:	goto yy100;
			}
yy332:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy333;
			default:	goto yy100;
			}
yy333:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy334;
			default:	goto yy100;
			}
yy334:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy335;
			default:	goto yy100;
			}
yy335:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy336;
			default:	goto yy100;
			}
yy336:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy337;
			}
yy337:
// 143 "scanner.re"
			{
			s->active_char += sizeof("function")-1;
			token->opcode = XX_T_FUNCTION;
			return 0;
		}
// 5203 "scanner.c"
yy338:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy339;
			}
yy339:
// 269 "scanner.re"
			{
			s->active_char += sizeof("for")-1;
			token->opcode = XX_T_FOR;
			return 0;
		}
// 5280 "scanner.c"
yy340:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy341;
			default:	goto yy100;
			}
yy341:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy342;
			default:	goto yy100;
			}
yy342:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy343;
			}
yy343:
// 215 "scanner.re"
			{
			s->active_char += sizeof("float")-1;
			token->opcode = XX_T_TYPE_DOUBLE;
			return 0;
		}
// 5371 "scanner.c"
yy344:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy345;
			default:	goto yy100;
			}
yy345:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy346;
			default:	goto yy100;
			}
yy346:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy347;
			}
yy347:
// 131 "scanner.re"
			{
			s->active_char += sizeof("final")-1;
			token->opcode = XX_T_FINAL;
			return 0;
		}
// 5462 "scanner.c"
yy348:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy349;
			default:	goto yy100;
			}
yy349:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy350;
			default:	goto yy100;
			}
yy350:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy351;
			}
yy351:
// 341 "scanner.re"
			{
			token->opcode = XX_T_FETCH;
			s->active_char += sizeof("fetch")-1;
			return 0;
		}
// 5553 "scanner.c"
yy352:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy353;
			default:	goto yy100;
			}
yy353:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy354;
			default:	goto yy100;
			}
yy354:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy355;
			}
yy355:
// 65 "scanner.re"
			{
			s->active_char += sizeof("false")-1;
			token->opcode = XX_T_FALSE;
			return 0;
		}
// 5644 "scanner.c"
yy356:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy364;
			default:	goto yy100;
			}
yy357:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'W':
			case 'w':	goto yy362;
			default:	goto yy100;
			}
yy358:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy359;
			default:	goto yy100;
			}
yy359:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy360;
			default:	goto yy100;
			}
yy360:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy361;
			}
yy361:
// 59 "scanner.re"
			{
			s->active_char += sizeof("null")-1;
			token->opcode = XX_T_NULL;
			return 0;
		}
// 5749 "scanner.c"
yy362:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy363;
			}
yy363:
// 281 "scanner.re"
			{
			s->active_char += sizeof("new")-1;
			token->opcode = XX_T_NEW;
			return 0;
		}
// 5826 "scanner.c"
yy364:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy365;
			default:	goto yy100;
			}
yy365:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy366;
			default:	goto yy100;
			}
yy366:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy367;
			default:	goto yy100;
			}
yy367:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy368;
			default:	goto yy100;
			}
yy368:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy369;
			default:	goto yy100;
			}
yy369:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy370;
			default:	goto yy100;
			}
yy370:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '\\':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy99;
			default:	goto yy371;
			}
yy371:
// 77 "scanner.re"
			{
			s->active_char += sizeof("namespace")-1;
			token->opcode = XX_T_NAMESPACE;
			return 0;
		}
// 5945 "scanner.c"
yy372:
			yych = *++YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy375;
			default:	goto yy113;
			}
yy373:
			yyaccept = 0;
			YYMARKER = ++YYCURSOR;
			yych = *YYCURSOR;
yy374:
			switch (yych) {
			case '.':	goto yy372;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy373;
			default:	goto yy5;
			}
yy375:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy375;
			default:	goto yy377;
			}
yy377:
// 50 "scanner.re"
			{
			token->opcode = XX_T_DOUBLE;
			token->value = strndup(start, YYCURSOR - start);
			token->len = YYCURSOR - start;
			s->active_char += (YYCURSOR - start);
			q = YYCURSOR;
			return 0;
		}
// 6006 "scanner.c"
yy378:
			++YYCURSOR;
// 630 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_DECR;
			return 0;
		}
// 6015 "scanner.c"
yy380:
			++YYCURSOR;
// 594 "scanner.re"
			{
			s->active_char += 2;
			token->opcode = XX_T_ARROW;
			return 0;
		}
// 6024 "scanner.c"
yy382:
			++YYCURSOR;
// 522 "scanner.re"
			{
			s->active_char++;
			token->opcode = XX_T_SUBASSIGN;
			return 0;
		}
// 6033 "scanner.c"
		}
// 677 "scanner.re"

	}

	return status;
}
