
#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "test/arithmetic.h"
#include "test/assign.h"
#include "test/cast.h"
#include "test/cblock.h"
#include "test/constants.h"
#include "test/constantsinterface.h"
#include "test/constantsparent.h"
#include "test/declare.h"
#include "test/echoes.h"
#include "test/exception.h"
#include "test/exceptions.h"
#include "test/fannkuch.h"
#include "test/fcall.h"
#include "test/fibonnaci.h"
#include "test/flow.h"
#include "test/fortytwo.h"
#include "test/mcall.h"
#include "test/mcallchained.h"
#include "test/nativearray.h"
#include "test/oo.h"
#include "test/oo/ooconstruct.h"
#include "test/oo/ooconstructparams.h"
#include "test/oo/oodynamica.h"
#include "test/oo/oodynamicb.h"
#include "test/oo/oonoconstruct.h"
#include "test/oo/ooparams.h"
#include "test/properties/privateproperties.h"
#include "test/properties/protectedproperties.h"
#include "test/properties/publicproperties.h"
#include "test/regexdna.h"
#include "test/returns.h"
#include "test/router.h"
#include "test/router/exception.h"
#include "test/router/route.h"
#include "test/scall.h"
#include "test/scallexternal.h"
#include "test/scallparent.h"
#include "test/spectralnorm.h"
#include "test/testinterface.h"

#endif