#!/usr/bin/env php
<?php

/**
 * This file is part of the Zephir.
 *
 * (c) Zephir Team <team@zephir-lang.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Zephir\Support\PhpUnitCommand;

require_once __DIR__ . '/../autoload.php';

if (!class_exists('\PHPUnit\TextUI\Command') and class_exists('PHPUnit_TextUI_Command')) {
    /** @noinspection PhpIgnoredClassAliasDeclaration */
    class_alias('PHPUnit_TextUI_Command', '\PHPUnit\TextUI\Command');
}

if (!class_exists('\PHPUnit\Framework\SkippedTestError') and class_exists('PHPUnit_Framework_SkippedTestError')) {
    /** @noinspection PhpIgnoredClassAliasDeclaration */
    class_alias('PHPUnit_Framework_SkippedTestError', '\PHPUnit\Framework\SkippedTestError');
}

if (!class_exists('\PHPUnit\Framework\MockObject\MockObject') and class_exists('PHPUnit_Framework_MockObject_MockObject')) {
    /** @noinspection PhpIgnoredClassAliasDeclaration */
    class_alias('PHPUnit_Framework_MockObject_MockObject', '\PHPUnit\Framework\MockObject\MockObject');
}

if (!class_exists(PhpUnitCommand::class)) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

PhpUnitCommand::start();
