#!/usr/bin/env php
<?php

/*
 * This file is part of the Zephir package.
 *
 * (c) Zephir Team <team@zephir-lang.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Zephir\Support\PhpUnitCommand;

require_once dirname(__DIR__) . '/bootstrap.php';
require_once __DIR__ . '/Zephir/Support/compat.php';

if (!class_exists(PhpUnitCommand::class)) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

PhpUnitCommand::start();
