#!/bin/bash
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/assign.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/arithmetic.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/nativearray.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/flow.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/fibonacci.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/oo.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/mcall.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/scall.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/properties.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/constants.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/exceptions.php
#php ./test/unit-tests/regexdna.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/fannkuch.php
valgrind --read-var-info=yes --fullpath-after= --track-origins=yes $(phpenv which php) ./test/unit-tests/scallexternal.php
