#!/bin/bash
export CC="gcc"
export CFLAGS="-O2 -Wall -fvisibility=hidden -fno-delete-null-pointer-checks -finline-functions -fno-builtin-memcmp -flto -DZEPHIR_RELEASE=1 -fprofile-use"

if [ -f .libs/%PROJECT_LOWER%.gcda ]; then
        cp .libs/%PROJECT_LOWER%.gcda .
else
        echo "Profile info was not found"
fi

if [ -f Makefile ]; then
	sudo make --silent clean
	sudo phpize --silent --clean
fi

phpize --silent
./configure --silent --enable-%PROJECT_LOWER%
make --silent && sudo make --silent install
