
#ifdef HAVE_CONFIG_H
#include "../../ext_config.h"
#endif

#include <php.h>
#include "../../php_ext.h"
#include "../../ext.h"

#include <Zend/zend_operators.h>
#include <Zend/zend_exceptions.h>
#include <Zend/zend_interfaces.h>

#include "kernel/main.h"


/**
 * Stub\Router\Exception
 *
 * Exceptions generated by the router
 */
ZEPHIR_INIT_CLASS(Stub_Router_Exception) {

	ZEPHIR_REGISTER_CLASS_EX(Stub\\Router, Exception, stub, router_exception, zend_exception_get_default(TSRMLS_C), NULL, 0);

	return SUCCESS;

}

